### ISSUE TITLE
complete nonsense with defines after https://github.com/jthornber/thin-provisioning-tools/pull/103

### ISSUE THREAD

**Issue by asavah** [jthornber/thin-provisioning-tools#105]
After https://github.com/jthornber/thin-provisioning-tools/pull/103
https://github.com/jthornber/thin-provisioning-tools/blob/master/block-cache/io_engine.h#L14-L23

```
if not defined PAGE_SIZE
  define PAGE_SIZE

if defined PAGE_SIZE
  undef PAGE_SIZE
```

good job :P

**Comment by jthornber** [comment]
Sorry, I've reverted that pull.  I'm on vacation atm, and didn't check that pull request sufficiently figuring if it broke something it would break hard.

**Comment by asavah** [comment]
Thx )
