### ISSUE TITLE
Definitions for thin_delta tags and data

### ISSUE THREAD

**Issue by tasket** [jthornber/thin-provisioning-tools#108]
Looking through the output of `thin_delta --verbose` there seem to be elements with obvious meanings and others that are more mysterious. The man pages don't provide definitions for any them, unfortunately. This leads me to ask the following questions:

1. `different` appears to show blocks that differ between snapshots. However, I don't know the significance of having two different numbers listed under `left_data_begin` and `right_data_begin`. I would have expected the block numbers to be the same, if they are referencing thin lv locations. I might guess the addresses differ because they are references to the parent pool volume instead?

2. `same` doesn't suggest any useful function to me. Is it superfluous? If so, an option to omit `same` in the output could yield a significant performance gain.

3. `left_only` and `right_only`: Do these show differences in block (de)allocation in each volume?

Thanks!

**Comment by tasket** [comment]
RE: Question 1....

I do need some way to translate these numbers to block addresses that make sense within a thin lv.

**Comment by jthornber** [comment]
1.  All thin volumes are mapped to data in the pool.  {left,right}_data_begin tell you where in the pool the data resides.  The 'begin' fields are the virtual addresses (ie. the location within the thin volume).

2.  It tells you where common mapped regions are, which might not be useful for your use case.  I'd be happy to take a patch for an option that skips it.  This is the relevant file:

    https://github.com/jthornber/thin-provisioning-tools/blob/master/thin-provisioning/thin_delta.cc

If performance is really an issue then we could think about supporting plugin libraries like I did with thin_dump (see contrib/).

3.  Yes, 'left_only' means those blocks are only mapped/allocated in the left thin etc.
