### ISSUE TITLE
thin_delta output is truncated to <4MB

### ISSUE THREAD

**Issue by tasket** [jthornber/thin-provisioning-tools#109]
Running the following commands in a dom0 VM (Xen):

```
sudo dmsetup message qubes_dom0-pool00-tpool 0 reserve_metadata_snap
sudo thin_delta -m --thin1 21078 --thin2 21238 /dev/mapper/qubes_dom0-pool00_tmeta >tdtest
sudo dmsetup message qubes_dom0-pool00-tpool 0 release_metadata_snap
```

Results in thin_delta output in 'tdtest' file with the referenced blocks in the `begin` property stopping in the neighborhood of 16064. Since the blocksize shown is 256, that means the reporting has stopped at the 4MB mark. Naturally, for most useful volume sizes (these are 2GB virtual in a 214GB pool) this would be useless.

Also, the `length` properties for the non-same tags (multiplied by 256) add up to only about 500kB, although this figure climbs slightly higher each time I change something in the `--thin2` volume. The actual differences between the two volumes range in the tens of megabytes.

I compiled and installed the newer version 0.7.6 over the older version supplied with the distro, but this didn't help. The distro is the Qubes-supplied Fedora 25 with dom0 kernel 4.14.57.

**Comment by jthornber** [comment]
block size is in 512byte sectors

**Comment by tasket** [comment]
The thin_delta report shows 256. This is in bytes?

```
<superblock uuid="" time="16457" transaction="43931" data_block_size="256" nr_data_blocks="0">
```

Even if it were 512 bytes, that would still leave the report truncated at 8MB.

**Comment by tasket** [comment]
It also occurred to be that `thin_check` has never been run on this pool to check for errors/consistency. I will try to run it from a live CD tonight.

**Comment by jthornber** [comment]
256 * 512bytes

**Comment by tasket** [comment]
Thanks.

Is the 512byte size a constant?

**Comment by jthornber** [comment]
yes, sectors in linux are specified in 512byte units

**Comment by tasket** [comment]
@jthornber Seems I've still got some issues with `data_block_size`.

In my own testing this size always reports as 256. But some testers are having issues because the delta size on some (not all) volumes is 512.

Can you elaborate on why - in very similar systems - the `data_block_size` is 512 for some thin_delta sets, and what is the range of values that my backup program could encounter?

The related issue is here https://github.com/tasket/sparsebak/issues/5

Thanks!

**Comment by jthornber** [comment]
The data block size is set when the thin pool is created.  The minimum value is 64 sectors (32kbytes), and the maximum is 2^21 (1 Gig).  If you are using many snapshots it's advisable to use a smaller block size to minimise wasted data when copy-on-write operations are triggered.  Otherwise larger blocks mean fewer mappings and so less metadata/memory use.

LVM is free to use what ever defaults it wants, or change that default.

More information about the thin pool target can be found here:

https://github.com/torvalds/linux/blob/master/Documentation/device-mapper/thin-provisioning.txt
