### ISSUE TITLE
autoreconf does not give $MANDIR a default value

### ISSUE THREAD

**Issue by itoffshore** [jthornber/thin-provisioning-tools#11]
Many Thx for the 2 commits today - it now compiles ok.

Running 'autoreconf' does not give $MANDIR a default value so the MAN pages are installed to $(DESTDIR)/man8. This can be fixed by setting the default value before running ./configure: 

    export MANDIR="/usr/share/man"

**Comment by vapier** [comment]
this is fixed in commit aa08c8393aa0236b67ac1b90c52137f94e3b2ed1
