### ISSUE TITLE
Invalid iterator operations in run_set::member()

### ISSUE THREAD

**Issue by mingnus** [jthornber/thin-provisioning-tools#112]
Two issues:

1. The returned iterator of runs_.lower_bound() is not checked
2. The iterator might went beyond the first element

The second point might be an undefined behavior in C++ specification, so it's better to check the position before doing it.

Patch for review: (test cases passed)
<pre>
--- a/persistent-data/run_set.h
+++ b/persistent-data/run_set.h
@@ -64,13 +64,13 @@ namespace base {
 
                        typename rset::const_iterator it = runs_.lower_bound(run<T>(v));
 
-                       if (it->begin_ == v)
+                       if (it != runs_.end() && it->begin_ == v)
                                return true;
 
-                       it--;
-
-                       if (it != runs_.end())
+                       if (it != runs_.begin()) {
+                               it--;
                                return it->contains(v);
+                       }
 
                        return false;
                }
</pre>

**Comment by jthornber** [comment]
Looks good. Thx
