### ISSUE TITLE
ft-lib/bcache.c can clash with signal.h

### ISSUE THREAD

**Issue by Polynomial-C** [jthornber/thin-provisioning-tools#123]
At Gentoo Linux we stumbled upon the following build issue after installing `libaio-0.3.112`:
```
x86_64-pc-linux-gnu-gcc -c -I. -I. -I./thin-provisioning -march=native -mtune=native -O2 -pipe -fPIC  -o ft-lib/bcache.o ft-lib/bcache.c
ft-lib/bcache.c:34:13: error: conflicting types for ‘raise’
 static void raise(const char *fmt, ...)
             ^~~~~
In file included from /usr/include/libaio.h:32,
                 from ft-lib/bcache.c:11:
/usr/include/signal.h:123:12: note: previous declaration of ‘raise’ was here
 extern int raise (int __sig) __THROW;
            ^~~~~
make: *** [Makefile:217: ft-lib/bcache.o] Error 1
```

which happens because `libaio-0.3.112` includes `<signal.h>` in its `libaio.h` file:
https://pagure.io/libaio/c/5e664cabd2a8cedd31afa9afbec11218011f9387

This was also reported as a bug in Debian:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=924844

with a proposed fix:
https://bugs.debian.org/cgi-bin/bugreport.cgi?att=1;bug=924844;filename=thin-provisioning-tools_0.7.6-2.1.diff;msg=10

**Comment by jthornber** [comment]
I just pushed a fix.
