### ISSUE TITLE
Code refactoring planning

### ISSUE THREAD

**Issue by mingnus** [jthornber/thin-provisioning-tools#128]
Hi Joe,

I've been working on some new features these days. I would like to do some tidy up:

1. Factor out the major code in thin_check to metadata_checker.cc. Now thin_check covers all the features of the obsolete code.
2. Add btree_damage_visitor.cc into the compilation.

Does that match your intention?

**Comment by jthornber** [comment]
i've got a lot of changes that i'll be pushing to metadata_dumper.cc and the thinp restore_emitter.  it sounds like your stuff won't interfere with that so go ahead.
