### ISSUE TITLE
Cache_writeback should not commit metadata?

### ISSUE THREAD

**Issue by pahome** [jthornber/thin-provisioning-tools#138]
I test v0.8.5 tools in Ubuntu 16.04 with kernel5.4.
When I tried cache commands, it always failed when use cache_writeback.
I found when it want to commit metadata, it says "px != 0".
After I dig in, I found that means member `metadata_sm_` of `class metadata` doesn't initialize.

Like below:
```
$> blockdev --getsz /dev/sdb // SSD
    937703088
$> blockdev --getsz /dev/sdc // SSD
    937703088

$> sudo dmsetup create test-dev-260074 --table "0 8192 linear /dev/sdb 0"
$> sudo dmsetup create test-dev-693500 --table "0 1048576 linear /dev/sdb 8192"
$> sudo dmsetup create test-dev-671419 --table "0 8388608 linear /dev/sdc 0"
$> sudo dd if=/dev/zero of=/dev/mapper/test-dev-260074 bs=512 count=8 seek=0
8+0 records in
8+0 records out
4096 bytes (4.1 kB, 4.0 KiB) copied, 0.000455244 s, 9.0 MB/s

$> sudo cache_xml create --block-size 64 --nr-cache-blocks 16384 --nr-mappings 16384 --dirty-percent 50 > metadata.xml

Restoring: [==================================================]   100%

$> sudo cache_writeback --metadata-device /dev/mapper/test-dev-260074 --fast-device /dev/mapper/test-dev-693500 --origin-device /dev/mapper/test-dev-671419 --buffer-size-meg 16

Copying data: [==================================================]   100%
8126/8126 blocks successfully copied.
Updating metadata ... clearing dirty flag for block 0
clearing dirty flag for block 2
clearing dirty flag for block 3
...
clearing dirty flag for block 2539
clearing dirty flag for block 2545

cache_writeback: /usr/include/boost/smart_ptr/shared_ptr.hpp:648: typename boost::detail::sp_member_access<T>::type boost::shared_ptr<T>::operator->() const [with T = persistent_data::checked_space_map; typename boost::detail::sp_member_access<T>::type = persistent_data::checked_space_map*]: Assertion `px != 0' failed.
Aborted (core dumped)


```

And the bug happend like below:
`caching/cache_writeback.cc `
```
void update_metadata(metadata &md, set<block_address> const &failed_writebacks) {
                cout << "Updating metadata ... ";
                ...
                for (block_address cblock = 0; cblock < mappings->get_nr_entries(); cblock++) {
                        auto m = mappings->get(cblock);
                        ...
                        cerr << "clearing dirty flag for block " << cblock << "\n";
                        mappings->set(cblock, m);
                }
                md.commit(true);  <--------------------- Enter from here
                cout << "done\n";
                cout.flush();
        }

```
Then enter into `md.commit()` below:
`caching/metadata.cc `
```
void metadata::commit(bool clean_shutdown)
{
        commit_space_map(); <------- commit space map
        commit_mappings();
        commit_hints();
        commit_discard_bits();
        commit_superblock(clean_shutdown);
}
void metadata::commit_space_map()
{
        metadata_sm_->commit(); //  failed here
        metadata_sm_->copy_root(&sb_.metadata_space_map_root, sizeof(sb_.metadata_space_map_root));
}

```

So, should the md.commit() need to remove to avoid this?

**Comment by jthornber** [comment]
Yes, there's a long standing bug in writeback.  For now you can work round
it by letting the kernel do the online writeback for you.

eg,

https://github.com/jthornber/device-mapper-test-suite/blob/master/lib/dmtest/tests/cache/background_writeback_tests.rb#L137

**Comment by pahome** [comment]
So I can remove the md.commit()

And ignore the cache_offline_writeback failed in ToolsTests of device-mapper-test-suite?

**Comment by jthornber** [comment]
There's a flag that tells it not to update the metadata.  So you can still
use cache_writeback to decommission a cache.

**Comment by pahome** [comment]
Sorry, I don't get it.

I think the normal procedures should be ok but failed because the metadata_sm_ isn't initialized .
You mean I can run cache_writeback with --no-metadata-update?
But how to solve problem of metadata_sm_which isn't initialized?

**Comment by jthornber** [comment]
If you think you have a fix, great.  Send me a pull request along with
details on how you tested it.

**Comment by pahome** [comment]
@jthornber 
What's the difference between online and offline writeback?
Only differ in updating metadata?

**Comment by jthornber** [comment]
For offline you have to deactivate the dm-cache device.

**Comment by pahome** [comment]
Can I ask why space_map will count counts[idx] greater than 1? not greater than 0?

In `persistent-data/transaction_manager.cc:`
```
pair<transaction_manager::write_ref, bool>
transaction_manager::shadow(block_address orig, validator v)
{
        bool need_inc = sm_->count_possibly_greater_than_one(orig); <---- Here
        if (is_shadow(orig) && !need_inc)
                return make_pair(bm_->write_lock(orig, v), need_inc);

        read_ref src = bm_->read_lock(orig, v);
        optional<block_address> mb = sm_->new_block();
        if (!mb)
                throw runtime_error("transaction_manager::shadow() couldn't allocate new block");
...
}
```

**Comment by jthornber** [comment]
If the count is zero, then no body is using it and you shouldn't be copying
it.

If the count is one, then there is only a single user, so by shadowing
you're releasing the old block and making an identical copy.  As such you
do not need to change the reference counts of any children, since the net
change is zero.

If the count is >1 then you need to increment the reference counts on all
children, the new copy will reference them.

**Comment by jthornber** [comment]
You may want to work on HEAD, since I removed
sm::count_possibly_greater_than_one() the other day, and there have been
some other space map fixes recently.

**Comment by pahome** [comment]
> You may want to work on HEAD, since I removed
Oh, no. It still failed when I do online cache_writeback.

> f the count is one, then there is only a single user, so by shadowing
> you're releasing the old block and making an identical copy.
What does shadowing mean and why need this when clearing the dirty flag?

**Comment by jthornber** [comment]
cache_writeback is for offline writeback.

To do online writeback you let the kernel driver clean up.  See the test
that I linked to earlier.

**Comment by pahome** [comment]
So the [step](https://github.com/jthornber/thin-provisioning-tools/issues/138#issue-629876081) I run was fault?

I should suspend them first, then do the following steps e.g. cache_restore -> cache_writeback?

**Comment by jthornber** [comment]
There is a bug in cache_writeback.  But it's generally not an issue because
the kernel driver writes back all the time.  There is a cleaner policy that
you can switch in if you wish to completely clean the cache (this will do
no promotions or demotions).  I have shown you test code that does this.

Why do you particularly want to do offline writeback?

**Comment by pahome** [comment]
I just want to test how to use cache_writeback, and my original procedures is like below:
```
cache_create
cache_restore
cache_writeback
```
But it failed with unknown reasons.

Is there any documents to tell how to use cache_XXXXX tools in what condition?

**Comment by jthornber** [comment]
cache_writeback only works with the --no-metadata-update flag set.

**Comment by pahome** [comment]
> If the count is one, then there is only a single user, so by shadowing
> you're releasing the old block and making an identical copy.  As such you
> do not need to change the reference counts of any children, since the net
> change is zero.

That means I only copy the data block and not update the ref counts of children if the count is one?

**Comment by jthornber** [comment]
Yes.  Are you writing a user land program now?

**Comment by pahome** [comment]
Not yet, now is to understand using cache_XXX tools correctly.
Then the next plan is user-spce program.
