### ISSUE TITLE
What does cache_dump repair with --repair

### ISSUE THREAD

**Issue by pahome** [jthornber/thin-provisioning-tools#140]
As title, cache_dump can repair whilst dumping from man page.

It says:

> -r, --repair
>        Repair the metadata whilst dumping it.

What does the option fix? all of metadata? or space map of metadata? or else?

**Comment by jthornber** [comment]
The XML contains a logical view of the metadata, as such it has no concept
of space maps.

The --repair flag causes thin_dump to make a best effort when dumping out
the data, for instance if it finds
corruption it will try and work round it rather than aborting.

**Comment by pahome** [comment]
> for instance if it finds corruption it will try and work round it rather than aborting.

But how to fix if space map corrupt or mapping corrupt?

**Comment by pahome** [comment]
Actually, --repair let the check "ignore" fatal and continuing dump message in cache_dump.

**Comment by jthornber** [comment]
Repairing is a two stage process.  First you cache_dump, then you cache
restore.

**Comment by pahome** [comment]
I know, I originally curious cache_dump with --repair can really repair what
