### ISSUE TITLE
Q: compare/get mapping of a thin provisioned LV?

### ISSUE THREAD

**Issue by phmarek** [jthornber/thin-provisioning-tools#15]
Is there a way to get the list of logical => physical block of a thin LV? AFAIU `thin_rmap` does something similar, but only for the metadata LV?

Furthermore, how can I check how similar two LVs (origin and snapshot) are? I'd like to see something like "C common chunks, M only in A, N only in B" or similar.

Last, but not least, a difference extent list would be nice; comparing a snapshot to the origin might give a list of extents (start, length) that are different.

Thanks for your patience!

**Comment by jthornber** [comment]
I think thin_ls and thin_delta cover this.
