### ISSUE TITLE
ref_counter typedef conflicts with persistent_data::ref_counter

### ISSUE THREAD

**Issue by ilyakurdyukov** [jthornber/thin-provisioning-tools#184]
In `persistent-data/data-structures/array.h`:

```c++
	template <typename ValueTraits>
	class array : public array_base {
	public:
		class block_ref_counter : public ref_counter<uint64_t> {
		public:
```

```c++
		typedef typename ValueTraits::ref_counter ref_counter;
```

The ambiguity here is whether the ref_counter name refers to `persistent_data::ref_counter` or `ValueTraits::ref_counter` from the later typedef.

This gives errors when using compilers based on EDG frontend, and their developers think your code is wrong, not the compiler.

Possible solution:

```patch
-		class block_ref_counter : public ref_counter<uint64_t> {
+		class block_ref_counter : public persistent_data::ref_counter<uint64_t> {
```

It's better not to use the same name everywhere.

**Comment by jthornber** [comment]
I just pushed your fix.  Thank you.
