### ISSUE TITLE
content_based_hash parameter initialization overflow

### ISSUE THREAD

**Issue by sallyjunjun** [jthornber/thin-provisioning-tools#202]
in content_based_hash constructor function, the window_size parameter is externally controllable. if the value of window_size is smaller than 4, then backup_div_ value is overflow. The input value of window_size should be checked.

**Comment by jthornber** [comment]
I don't think this code is used in anything.  What prompted you to look at it?

**Comment by sallyjunjun** [comment]
I've seen that this window_size is initialized in thin-provisioning/thin_show_duplicates.cc with 'variable_chunk_stream vstream(stream, 4096);' . The window_size is set to 4096 with hard code. I just think that if it is initiallized elsewhere with other values, it may cause interger overflow problew without check.
