### ISSUE TITLE
Question about tests directory and functional-tests directory

### ISSUE THREAD

**Issue by sallyjunjun** [jthornber/thin-provisioning-tools#208]
I want to ask what's the difference between tests and functional-tests. Is tests directory the reconstruction of functional-tests directory? Will the functional-tests directory be deprecated in the future？

**Comment by jthornber** [comment]
I'm trying to reduce the number of languages that we use in this project.  So the Scheme functional tests are being replaced with the Rust ones in tests/.  Soon all the Scheme and C++ code will disappear.

**Comment by sallyjunjun** [comment]
you mean the unit tests and functional tests will all be replaced with the rust in tests/ ?

**Comment by jthornber** [comment]
All C++ will go, the tools have been rewritten in Rust.

**Comment by sallyjunjun** [comment]
Ok, thank you for your explanation.
