### ISSUE TITLE
thin-provisioning-tools-0.4.1 fails due to incorrect operator?

### ISSUE THREAD

**Issue by yuyuyak** [jthornber/thin-provisioning-tools#22]
Funtoo emerge failed repeatedly with this:
thin-provisioning/thin_metadata_size.cc: In function ‘void print_precision(global*, double, unsigned int)’:
thin-provisioning/thin_metadata_size.cc:327:26: error: ‘truncl’ was not declared in this scope
  double rtrunc = truncl(r);

                     ^
distcc[31683] ERROR: compile thin-provisioning/thin_metadata_size.cc on localhost failed
I've forgotten most of that Introductory C class 35 years ago, but looking up trunc, truncf, truncl operators it tells me that truncl is to be used on long doubles, in this case it should be trunc?  Anyhow, I patched it to that and it compiled fine.
Amazingly, this flew through x86 and x86_64 installs just fine, but my arm platform kicked it out.
Thanks for your work.

**Comment by yuyuyak** [comment]
This issue still occurs on my ARM devices with version 0.5.3.  After patching, installs fine.

**Comment by MrStaticVoid** [comment]
Just wanted to chime in to say I am also seeing this compilation failure on my Funtoo RaspberryPis and Beaglebones Black.

**Comment by jthornber** [comment]
Could you try again with this commit please?

https://github.com/jthornber/thin-provisioning-tools/commit/7134a581340d798ba56fd48629edb4c59501d761

**Comment by yuyuyak** [comment]
Thank you jthornber, it compiles perfectly with that commit.
Note that I am not using thin-provisioning-tools, it's part of the lvm metapackage here and I currently am not using lvm (crazy I know).  So I can only vouch for the fact that it compiles without error, not usability.
Thanks again for your hard work.

**Comment by vapier** [comment]
time to close then ? :)

**Comment by yuyuyak** [comment]
Yes, thank you.  Learning all the time ...
