### ISSUE TITLE
Version 1.0.0 does not activate my thinpool.

### ISSUE THREAD

**Issue by ewtoombs** [jthornber/thin-provisioning-tools#244]
When I run `vgchange -ay`, I get the following error message:
```
Check of pool myvgnamehere/mythinpoolnamehere failed (status:64). Manual repair required!
```
My system won't boot with 1.0.0 because of this. Reverting to 0.9.0 fixes the problem.

**Comment by mingnus** [comment]
Hi,

Could you help provide the thin_check outputs for your pool metadata please? Thanks.
I recommend using the v1.0.0 for the check.

```
## Deactivate the pool
# lvchange -an myvgnamehere/mythinpoolnamehere

## Activate the pool metadata read-only
# lvchange -ay myvgnamehere/mythinpoolnamehere_tmeta

## thin_check the pool metadata
# thin_check /dev/mapper/myvgnamehere-mythinpoolnamehere_tmeta

## Deactivate the pool metadata after checking
# lvchange -an myvgnamehere/mythinpoolnamehere_tmeta
```

**Comment by miojonka** [comment]
Some, but not all systems seem to have the same issue here. Still investigating the difference and collecting data.

One system just has one PV, one VG and one thinpool with a single thin volume for root, it works fine with 0.9.0 and fails to boot with 1.0.0.

**Comment by mingnus** [comment]
The new version performs a more comprehensive check over the metadata, which might be the reason why thin_check returns non-zero on metadata with minor issues not captured by previous versions (e.g., leaked data blocks). If you have trouble with the new version, send me the thin_check logs, and I'll help it out.

**Comment by ewtoombs** [comment]
> Could you help provide the thin_check outputs for your pool metadata please?

@mingnus It is my root volume. I can't just deactivate it. I will need to boot into a recovery environment. Or, is there a way for me to get some basic data to you without having to deactivate the volume?

**Comment by ewtoombs** [comment]
OK, @mingnus , it took some doing, but I did the thin_check in recovery mode with 1.0.0. Here is the result:

```
TRANSACTION_ID=2
METADATA_FREE_BLOCKS=21274
Checking thin metadata
device details tree
mapping tree
data space map
5508 data blocks have leaked.
metadata space map
data space map contains leaks
```

**Comment by mingnus** [comment]
> OK, @mingnus , it took some doing, but I did the thin_check in recovery mode with 1.0.0. Here is the result:
> 
> ```
> TRANSACTION_ID=2
> METADATA_FREE_BLOCKS=21274
> Checking thin metadata
> device details tree
> mapping tree
> data space map
> 5508 data blocks have leaked.
> metadata space map
> data space map contains leaks
> ```

That's certainly data block leaks, which is non-harmful and can be fixed automatically. Unmark the `thin_check_options` line in `/etc/lvm/lvm.conf`, then append the `--auto-repair` option:

```
# Configuration option global/thin_check_options.
thin_check_options = [ "-q", "--auto-repair" ]
```

(The `--auto-repair` option implies `--clear-needs-check-flag`, so I remove the latter)

If you don't want to perform any fix at system startup, you can choose to ignore those minor errors:

```
# Configuration option global/thin_check_options.
thin_check_options = [ "-q", "--ignore-non-fatal-errors" ]
```

If you have any further questions, please let me know.

**Comment by ewtoombs** [comment]
`--auto-repair` has fixed it. Thank you, @mingnus !

Just a note, though, that at least for archlinux users relying on the lvm2 hook, `# mkinitcpio -p linux` must be rerun in order for this to work. This is because the new `/etc/lvm/lvm.conf` must be still copied over to the initramfs.

**Comment by mingnus** [comment]
> `--auto-repair` has fixed it. Thank you, @mingnus !
> 
> Just a note, though, that at least for archlinux users relying on the lvm2 hook, `# mkinitcpio -p linux` must be rerun in order for this to work. This is because the new `/etc/lvm/lvm.conf` must be still copied over to the initramfs.

Great, and thanks for the information.

> Do you know whether `--auto-repair` could be used as a default for the distribution, @mingnus ?

One of the concerns should be, the underlying disks might be read-only and thus thin_check cannot open the metadata in writable mode. I'll talk with LVM maintainers later.

**Comment by pfactum** [comment]
`--auto-repair` made my system bootable again, thank you.

Is it safe to remove this switch after successful booting? How do those data block leaks appear at all?

**Comment by jthornber** [comment]
On Fri, 10 Feb 2023 at 15:50, Oleksandr Natalenko ***@***.***>
wrote:

> --auto-repair made my system bootable again, thank you.
>
> Is it safe to remove this switch after successful booting?
>
Yes

> How do those data block leaks appear at all?
>
Normally if the machine crashes during the window between allocating some
data blocks and committing the transaction.  Data leaks are harmless, you
just lose some space in the pool until it's fixed.

- Joe
 Message ID: ***@***.***
.com>

>

**Comment by ewtoombs** [comment]
> Normally if the machine crashes during the window between allocating some data blocks and committing the transaction.

In that case, @jthornber , for systems whose root is running off a thinpool, shouldn't `--auto-repair` stay in the defaults, even after the system is booting again? After all, a crash can happen at any time. I don't much fancy having to boot off of a USB drive and doing an `--auto-repair` there every time my system crashes.

**Comment by jthornber** [comment]
Yes, I would always run with --auto-repair, but it's up to the distro
maintainers.

**Comment by johnnyjeannatasha** [comment]
Status check

**Comment by ewtoombs** [comment]
> Status check

I don't know what the status is, @johnnyjeannatasha . As far as I know, `--auto-repair` is still required in thin_check_options for error recovery to happen at boot. I would have to add some trivial corruption to my thinpool and get rid of `--auto-repair` just to see if it still need to be there. I would rather not have to do that lol.

**Comment by jthornber** [comment]
I'm not sure what more you want from us.  Use --auto-repair to auto repair leaked data blocks.

**Comment by ewtoombs** [comment]
Yeah, that's fine, @jthornber . The only question that remains is whether it should be the default.

**Comment by jthornber** [comment]
I don't think a tool called 'check' should modify the device by default.  This is consistent with the fsck tools; eg, you need to pass -p to fsck.ext4 to get it to 'preen' the fs.

That said I do think the distros should use the --auto-repair flag.
