### ISSUE TITLE
unknown command thin_trim 

### ISSUE THREAD

**Issue by nobluesky** [jthornber/thin-provisioning-tools#26]
i built it from master branch. 
but i can't run thin_trim

Unknown command 'thin_trim'
Usage: <command> <args>
commands:
  cache_check
  cache_dump
  cache_metadata_size
  cache_restore
  cache_repair
  era_check
  era_dump
  era_invalidate
  era_restore
  thin_check
  thin_delta
  thin_dump
  thin_metadata_size
  thin_restore
  thin_repair
  thin_rmap

**Comment by tyll** [comment]
This is a duplicate of #24
