### ISSUE TITLE
Static buidling

### ISSUE THREAD

**Issue by thanosz** [jthornber/thin-provisioning-tools#266]
Is it possible to build a static pdata_tools binary? I need to compile an old c++ version: v0.4.1

**Comment by mingnus** [comment]
The Makefile in v0.4.1 doesn't support static build flags. You might have to backport commits dc08c78b, 244405ed, 3464f005, 431f2ab5, then turn on static build via configure:
```
./configure --enable-static --enable-static-cxx
```
