### ISSUE TITLE
btree_damage_visitor doesn't check value size

### ISSUE THREAD

**Issue by mingnus** [jthornber/thin-provisioning-tools#27]
I think it should be better to check the tree node's value size in btree_damage_visitor::check_internal() and btree_damage_visitor::check_leaf(). Otherwise, thin_check will report incorrect damage tracking if the first leaf of a device has wrong value size: The node still passed to btree_damage_visitor::good_leaf() in this case.

Here's the patch draft (seems a little ugly since I made node_ref::check_fits_within_block() to public):

<pre><code>
diff --git a/persistent-data/data-structures/btree.h b/persistent-data/data-structures/btree.h
index f4130c7..9e8a041 100644
--- a/persistent-data/data-structures/btree.h
+++ b/persistent-data/data-structures/btree.h
@@ -161,9 +161,9 @@ namespace persistent_data {
                                return raw_;
                        }
 
+                       void check_fits_within_block() const;
                private:
                        static unsigned calc_max_entries(void);
-                       void check_fits_within_block() const;
 
                        void *key_ptr(unsigned i) const;
                        void *value_ptr(unsigned i) const;
diff --git a/persistent-data/data-structures/btree_damage_visitor.h b/persistent-data/data-structures/btree_damage_visitor.h
index 1eede99..81cce26 100644
--- a/persistent-data/data-structures/btree_damage_visitor.h
+++ b/persistent-data/data-structures/btree_damage_visitor.h
@@ -212,6 +212,7 @@ namespace persistent_data {
                                    check_block_nr(n) &&
                                    check_max_entries(n) &&
                                    check_nr_entries(n, loc.is_sub_root()) &&
+                                   check_value_size(n) &&
                                    check_ordered_keys(n) &&
                                    check_parent_key(loc.is_sub_root() ? boost::optional<uint64_t>() : loc.key, n)) {
                                        if (loc.is_sub_root())
@@ -231,6 +232,7 @@ namespace persistent_data {
                                    check_block_nr(n) &&
                                    check_max_entries(n) &&
                                    check_nr_entries(n, loc.is_sub_root()) &&
+                                   check_value_size(n) &&
                                    check_ordered_keys(n) &&
                                    check_parent_key(loc.is_sub_root() ? boost::optional<uint64_t>() : loc.key, n)) {
                                        if (loc.is_sub_root())
@@ -322,6 +324,17 @@ namespace persistent_data {
                        }
 
                        template <typename node>
+                       bool check_value_size(node const &n) {
+                               try {
+                                       n.check_fits_within_block();
+                               } catch (std::exception &e) {
+                                       report_damage(e.what());
+                                       return false;
+                               }
+                               return true;
+                       }
+
+                       template <typename node>
                        bool check_ordered_keys(node const &n) {
                                unsigned nr_entries = n.get_nr_entries();
</code></pre>

**Comment by jthornber** [comment]
Thanks.  I tidied your patch up a bit to remove the explicit try/catch.

https://github.com/jthornber/thin-provisioning-tools/commit/85d1701ba1a0c246c9eca31a6c921b59972c8504
