### ISSUE TITLE
damage_tracker doesn't reset when damage_tracker::end() was called.

### ISSUE THREAD

**Issue by mingnus** [jthornber/thin-provisioning-tools#28]
Side effect in thin_check: If a device has broken mapping from key#N to the end of the device, then damage_tracker will report [N, 0] as broken while traversing the next device. For example,

<pre><code>
  thin device 1 is missing mappings [1234, -]
  thin device 2 is missing mappings [1234, 0]  // this line is wrong
  thin device 2 is missing mappings [3456, 5678]
</code></pre>

Here's the patch. I'm not sure whether damage_begin_ should be reset or not.

<pre><code>
diff --git a/persistent-data/data-structures/btree_damage_visitor.h b/persistent-data/data-structures/btree_damage_visitor.h
index 81cce26..77ac5fc 100644
--- a/persistent-data/data-structures/btree_damage_visitor.h
+++ b/persistent-data/data-structures/btree_damage_visitor.h
@@ -70,10 +70,15 @@ namespace persistent_data {
                        }
 
                        maybe_run64 end() {
-                               if (damaged_)
-                                       return maybe_run64(damage_begin_);
-                               else
-                                       return maybe_run64();
+                               maybe_run64 r;
+
+                               if (damaged_) {
+                                       r = maybe_run64(damage_begin_);
+                                       damaged_ = false;
+                               }
+
+                               damage_begin_ = 0;
+                               return r;
                        }
 
                private:
</code></pre>

**Comment by jthornber** [comment]
Ack.  Commit with unit test:

https://github.com/jthornber/thin-provisioning-tools/commit/880785a9bfa4f1adad701f03a13f575ca86433d0
