### ISSUE TITLE
Custom thin_dump emitter does not work

### ISSUE THREAD

**Issue by KJ7LNW** [jthornber/thin-provisioning-tools#280]
We're testing v1.0.6 and ran into an issue the custom emitter we contributed back in 2016 in commited 83dc84f790985b13e54864255b1e8693dbf3b8b6 .  We get this error:

```
# thin_dump -f custom=/usr/lib64/ewheeler_emitter.so --dev-id 608239 -m /dev/mapper/data-pool0_tmeta-thindump
error: invalid value 'custom=/usr/lib64/ewheeler_emitter.so' for '--format <TYPE>'
  [possible values: xml, human_readable]
```

A quick grep of the code makes it looks like custom emitters are no longer supported (likely due to the Rust port), but the option is still listed in the man page:

```
[root@dev thin-provisioning-tools]# git grep custom
CHANGES:- support custom emitter plugins for thin_dump.
COPYING:    customarily used for software interchange.
COPYING:    long as you offer spare parts or customer support for that product
COPYING:    medium customarily used for software interchange, for a price no
man8/thin_dump.txt:  -f, --format {xml|human_readable|custom}   Choose output format.
man8/thin_dump.txt:      $ thin_dump --format custom=mylib.so /dev/sda
src/copier/rescue_copier.rs:            .custom_flags(libc::O_EXCL | libc::O_DIRECT)
src/copier/rescue_copier.rs:            .custom_flags(libc::O_EXCL | libc::O_DIRECT)
src/copier/sync_copier.rs:            .custom_flags(libc::O_EXCL | libc::O_DIRECT)
src/copier/sync_copier.rs:            .custom_flags(libc::O_EXCL | libc::O_DIRECT)
src/io_engine/async_.rs:            .custom_flags(flags)
src/io_engine/spindle.rs:            .custom_flags(if excl {
src/io_engine/sync.rs:            .custom_flags(if excl {
src/pack/toplevel.rs:        .custom_flags(libc::O_EXCL)
src/thin/shrink.rs:        .custom_flags(libc::O_EXCL)
tests/cache_writeback.rs:            .custom_flags(libc::O_EXCL | libc::O_DIRECT)
tests/cache_writeback.rs:
```

and thin_dump.rs appears to confirm that:
```rs
#[derive(Clone)]
pub enum OutputFormat {
    XML,
    HumanReadable,
}
```

What would it take to support a custom emitter?

--
Eric Wheeler

**Comment by jthornber** [comment]
Let me look next week.  I don't think it's much work.

**Comment by KJ7LNW** [comment]
Thanks for your quick response!

FYI: We fixed it on our side with a small perl script to remap the XML to what we need.  If you are still interested in adding custom .so writer support, then great, but if not then please feel free to close the issue.

**Comment by jthornber** [comment]
I'm not sure what you're using the custom emitter for; but you may be
interested in my blkarchive project.

**Comment by KJ7LNW** [comment]
Thanks,  I'll check it out!

**Comment by mingnus** [comment]
Hi Eric,

I didn't port your custom emitter since we were not expecting it is still in-use, and the motivation of those custom emitters now could be better handled by blkarchive. If there're still other use cases of thin_dump or backups, please let us know.

**Comment by jthornber** [comment]
Eric,

I've just pushed a new file examples/custom-emitter.rs that shows you how to create your own thin_dump variant.  Would this approach work for you?  I can help with the Rust if need be.

**Comment by KJ7LNW** [comment]
@jthornber: perfect, that looks great.  How would the module be invoked on the cmdline?  Same as before with `--format custom=foo.so` ?

**Comment by KJ7LNW** [comment]
@mingnus, we were using per-device thin meta dumps as a safety mechanism in case we completely loose our tmeta.  Then we can use a script like below to extract the "lost" volume from tdata with the tmeta archive.  

Does thin-provisioning-tools already have a tool like "thin_extract" to rip volumes from tdata based on a tmeta dump?

Our meta format is `<origin_offset>:<length>:<tdata_offset>` in bytes (not chunks).  Here is the simple restore script:

```perl
use warnings;
use strict;
use Fcntl qw/SEEK_CUR SEEK_SET SEEK_END/;
use IO::Select;
use IO::Handle;
use Getopt::Long qw(:config bundling);

my ($tdata, $offset_file, $outfile);

GetOptions (
	"tdata=s"	=> \$tdata,
	"offsets=s"	=> \$offset_file,
	"output=s"	=> \$outfile
) or die "Error in command line arguments\n";

if (! $tdata ||  ! $offset_file || ! $outfile) {
	print "Usage: $0 --tdata /path/to/tdata --offsets /path/to/offset_file.gz --output /path/to/output_file\n";
	print "  --output can be a block device or a file. Note that only non-zero blocks are written, so\n";
	print "   if you are writing to a block device, it must be zeroed first (if you care).\n";
	exit 1
}

my $blk_size = 1024*64;

my %temp;
my @unsorted;
my @offsets;
my $index = 0;
my $size = 0;

if (! open(FH, "gzip -dc $offset_file |")) {
	print STDERR "Could not open offset file $offset_file!\n";
	exit 1;
}

foreach my $line (<FH>) {
	chomp $line;
	@temp{ qw/ooff len doff/ } = split /:/, $line;
	$unsorted[$index][0] = $temp{ooff};
	$unsorted[$index][1] = $temp{doff};
	$unsorted[$index][2] = $temp{len};
	$index++;
}
close(FH);

@offsets = sort { $a->[0] <=> $b->[0] } @unsorted;
$size = $offsets[$#offsets][2] + $offsets[$#offsets][0];
@offsets = sort { $a->[1] <=> $b->[1] } @unsorted;

my $seek = $size/1024 - 1;

system("dd if=/dev/zero bs=1024 seek=$seek count=1 of=$outfile &> /dev/null");

open(my $in, "<", $tdata) or die $!;
open(my $out, ">", $outfile) or die $!;
foreach my $line (@offsets) {
	my $read;
	my $s;
	sysseek($in, $line->[1], SEEK_SET);
	my $ni = sysread($in, $s, $line->[2]);

	if ($ni ne $line->[2]) {
		print STDERR "Number of bytes read differs from expected! $ni vs $line->[2].\n";
		close($in);
		close($out);
		exit 1;
	}

	sysseek($out, $line->[0], SEEK_SET);
	my $no = syswrite($out, $s, $line->[2]);

	if ($no ne $line->[2]) {
		print STDERR "Number of bytes written differs from expected! $ni vs $line->[2].\n";
		close($in);
		close($out);
		exit 1;
	}
}

close($in);
close($out);
exit;
```

**Comment by jthornber** [comment]
On Mon, 2 Oct 2023 at 20:38, KJ7LNW ***@***.***> wrote:

> Does thin-provisioning-tools already have a tool like "thin_extract" to
> rip volumes from tdata based on a tmeta dump?
>
>
See blkarchive:
    https://github.com/jthornber/blk-archive

A sample script using blkarchive to make incremental backups using
snapshots:

https://github.com/jthornber/blk-archive/blob/main/scripts/rolling-snaps-test

Message ID: ***@***.***
com>
>
>

**Comment by KJ7LNW** [comment]
I see that, looks great.  

Lets say you _only_ have access to the output of `thin_dump -f xml --dev-id 123  ...` for a single volume, and the `pool_tdata` volume (ie, the _tmeta volume is dead).  

Can blk-archive extract the single dev-id "123" from pool_tdata, or does it expect the _tmeta volume to be online?

**Comment by mingnus** [comment]
blkarchive only works with good _tmeta afaik. Given your use case (restore thin-volumes from the previous thin_dump outputs), it would be smarter to backup the volumes regularly using blkarchive, rather than keep the thin_dump outputs separately. Although running thin_dump alone is faster than blkarchive, there might be a risk that the thin_dump outputs are out-of-sync if you delete those thin volumes accidentally, and you never knows that while restoring. I would recommend blkarchive for the volume backup purpose.

**Comment by mingnus** [comment]
> @jthornber: perfect, that looks great. How would the module be invoked on the cmdline? Same as before with `--format custom=foo.so` ?

The custom-emitter is a stand-alone binary.  Build & run in this way:

```
cargo build --release --examples
./target/release/examples/custom-emitter --dev-id 1 tmeta.bin
```

**Comment by jthornber** [comment]
thin_dump output can go out of date immediately for thin devices that are
live.  For instance you might delete a file on 'thin1', which would cause a
discard to be sent to thin and underlying data blocks freed.  Then 'thin2'
might need to allocate data blocks and so reuse those previously freed
blocks.  If you used an old thin_dump you would end up with a device that
contained data from both 'thin1' and 'thin2'.  Don't do this.  If you want
to take backups use blk-archive; it's very fast when doing incremental
backups and does an excellent job of compressing and deduping your data.

**Comment by KJ7LNW** [comment]
Of course, you wouldn't try to dump a live volume, that would be silly.  

Thanks, both @jthornber and @mingnus, you've answered my questions.

**Comment by jthornber** [comment]
On Tue, 3 Oct 2023 at 07:10, KJ7LNW ***@***.***> wrote:

> Of course, you wouldn't try to dump a live volume, that would be silly.
>
If you are storing the dumps for any length of time you may want to look at
thin_metadata_{pack/unpack} too.  They crunch the whole metadata very
quickly, and to a fraction of the size.


Message ID: ***@***.***
com>
>
>

**Comment by KJ7LNW** [comment]
> If you are storing the dumps for any length of time you may want to look at
thin_metadata_{pack/unpack} too.  They crunch the whole metadata very
quickly, and to a fraction of the size.

Oh, thanks for the hint!  That sounds like a really good idea.  We save yearly snapshots that sit around for quite a while.

**Comment by KJ7LNW** [comment]
Hey @jthornber, we have always issued a meta snapshot as follows:

```
dmsetup suspend data-pool0-tpool
dmsetup message data-pool0-tpool 0 reserve_metadata_snap
dmsetup resume data-pool0-tpool
```

Is the suspend/resume cycle actually necessary, or is `reserve_metadata_snap` atomic such that it is safe to do without suspend/resume?

**Comment by jthornber** [comment]
No, you do not need to suspend the pool.
