### ISSUE TITLE
cargo.lock not updated on v1.0.8 tag

### ISSUE THREAD

**Issue by ReillyBrogan** [jthornber/thin-provisioning-tools#284]
Hello! I was updating our t-p-t package on Solus linux and got a build failure when trying to build from the autogenerated source archive (https://github.com/jthornber/thin-provisioning-tools/archive/refs/tags/v1.0.8.tar.gz) and got a failure during the build. We build using the following commands (for reproducibility):

```
cargo fetch --locked
cargo build --frozen --release
```

Which fails at the `cargo fetch` step with:
```
error: the lock file /home/build/YPKG/root/thin-provisioning-tools/build/thin-provisioning-tools-1.0.8/Cargo.lock needs to be updated but --locked was passed to prevent this
If you want to try to generate the lock file without accessing the network, remove the --locked flag and use --offline instead.
```

Now obviously this is something that I can workaround for now but I just wanted to bring it to your attention since preferably this wouldn't happen in the first place. Perhaps there could be a CI step to ensure that the cargo.lock is always valid for the cargo.toml? I think `cargo check --locked` would accomplish this without adding too much to a CI pipeline.

**Comment by jthornber** [comment]
Thanks, will fix.

**Comment by mingnus** [comment]
I'll update the pre-commit configuration to have `Cargo.lock` checked.  The `cargo clippy --locked` covers the features of `cargo check --locked` I think.
