### ISSUE TITLE
btree lower_bound_search::search() doesn't return error if the key is not found

### ISSUE THREAD

**Issue by mingnus** [jthornber/thin-provisioning-tools#29]
Hi Joe,

I found a potential bug in btree key search: The function lower_bound_search::search() doesn't check the return value of node_ref::lower_bound(). It will cause error if node_ref::lower_bound() returns -1 when the target key is lower than key_at(0). I think that the code should be modified as following, similar to node_ref::exact_search():

<pre><code>
--- a/persistent-data/data-structures/btree.tcc
+++ b/persistent-data/data-structures/btree.tcc
@@ -452,7 +452,10 @@ namespace persistent_data {
                template <typename ValueTraits>
                struct lower_bound_search {
                        static boost::optional<unsigned> search(btree_detail::node_ref<ValueTraits> n, uint64_t key) {
-                               return n.lower_bound(key);
+                               int i = n.lower_bound(key);
+                               if (i < 0)
+                                       return boost::optional<unsigned>();
+                               return boost::optional<unsigned>(i);
                        }
                };
</code></pre>

Also, in btree_damage_visitor, should the rule of check_parent_key() be this? 
<pre><code>if (*key != n.key_at(0))</code></pre>
Now it's
<pre><code>if (*key > n.key_at(0))</code></pre>.

Thanks

**Comment by mingnus** [comment]
Another related issue is, btree::lookup_raw() uses unsigned to receive the signed integer returned by node_ref::lower_bound(). We might consider to declare another integer variable to solve the issue.

**Comment by jthornber** [comment]
Committed lower_bound_search change.

https://github.com/jthornber/thin-provisioning-tools/commit/cf903cfea62c59f92e2e50bfe64b893f7e23db55

check_parent_key() is correct though, the btree constraints only promise the child keys are higher.

**Comment by jthornber** [comment]
and this commit ...

https://github.com/jthornber/thin-provisioning-tools/commit/c8d8af488fa9c72f98a9644952c56bdd4250ed7a
