### ISSUE TITLE
no data recovery possible with version 0.9 and latest 1.0.12

### ISSUE THREAD

**Issue by infphq** [jthornber/thin-provisioning-tools#306]
After following recovery guide and reading documentation here and issues too we were not able to recover two of our lost volumes.
Logs attached to document the issue and the process we did.
Please let us know if we did something differently or there must be an improvement to the program.
[LVM-ilsvm03.notes.txt](https://github.com/user-attachments/files/15515445/LVM-ilsvm03.notes.txt)

**Comment by infphq** [comment]
Thank you for your help!
Please find meta0.pack.tar.gz file here:
https://nc.parkinghq.com/index.php/s/kiC9Z7wX9oTKQF8

The two volumes got removed with lvremove (at least this is what Proxmox uses when you select this from WebGUI
Also one thing which got our attention is the output of vgmknodes (see attached log from post before):

root@proxmox:/# vgmknodes -vvv dataslow
...
      Processing LV vm-3004-disk-0 in VG dataslow.
        dm mknodes dataslow-vm--3004--disk--0  [ noopencount noflush ]   [2048] (*1)
        dataslow-vm--3004--disk--0: Stacking NODE_DEL
        Syncing device names
        dataslow-vm--3004--disk--0: Processing NODE_DEL
      Processing LV vm-3010-disk-0 in VG dataslow.
        dm mknodes dataslow-vm--3010--disk--0  [ noopencount noflush ]   [2048] (*1)
        dataslow-vm--3010--disk--0: Stacking NODE_DEL
        Syncing device names
        dataslow-vm--3010--disk--0: Processing NODE_DEL
      Processing LV dataslow_meta0 in VG dataslow.
...
There is a NODE DEL instead of a NODE ADD.

**Comment by mingnus** [comment]
> The two volumes got removed with lvremove (at least this is what Proxmox uses when you select this from WebGUI

Do you mean the thin volumes `vm-3004-disk-0` and `vm-3010-disk-0` accidentally got removed by Proxmox, and now you wish to recover the two volumes?  If it is true, then I guess now the two volumes in LVM was restored by vgcfgrestore right?

Could you please help provide the LVM archive & backup (`/etc/lvm/backup/*`, `/etc/lvm/archive/*`) for us to see what happened to LVM?

> Also one thing which got our attention is the output of vgmknodes (see attached log from post before):

It's normal that you see `NODE DEL` actions for inactivated volumes. The `vgmknodes` command synchronizes sysfs entries with in-kernel dm devices, so it intends to delete the device nodes for those inactivated volumes.

**Comment by infphq** [comment]
Here is the config:
https://nc.parkinghq.com/index.php/s/EtfMYHH8KoQEi5d

The two volumes vm-3004-disk-0 and vm-3010-disk-0 got accidentally removed by human in Proxmox, now we try to recover them.
After a backup of the original vgcfg we tried to restore from a point where everything was ok. After that there was a mismatch in the transaction_id we tried to circumvent by changing the ID to the expected one. After that we got the "No data available" message:

root@proxmox:/# vgcfgbackup -f /root/dataslow-orig.vg
root@proxmox:/# vgcfgrestore dataslow --file /root/dataslow_00011-51758151.vg --force
WARNING: Forced restore of Volume Group dataslow with thin volumes.
Restored volume group dataslow.
root@proxmox:/# lvscan
inactive '/dev/dataslow/dataslow' [1.79 TiB] inherit
inactive '/dev/dataslow/vm-3004-disk-0' [96.00 GiB] inherit
inactive '/dev/dataslow/vm-3010-disk-0' [96.00 GiB] inherit
inactive '/dev/pve/data' [265.18 GiB] inherit
inactive '/dev/pve/swap' [64.00 GiB] inherit
inactive '/dev/pve/root' [96.00 GiB] inherit
inactive '/dev/pve/data_meta0' [2.71 GiB] inherit

root@proxmox:/# vgchange -ay dataslow
Thin pool dataslow-dataslow-tpool (252:3) transaction_id is 6, while expected 4.
Thin pool dataslow-dataslow-tpool (252:3) transaction_id is 6, while expected 4.
Thin pool dataslow-dataslow-tpool (252:3) transaction_id is 6, while expected 4.
1 logical volume(s) in volume group "dataslow" now active

vim /root/dataslow-orig1.vg
---
logical_volumes {

dataslow {
id = "PAFvhv-HoTS-HNl9-vIln-Hn4s-9owL-dmqTRR"
status = ["READ", "WRITE", "VISIBLE"]
flags = []
creation_time = 1603115048 # 2020-10-19 13:44:08 +0000
creation_host = "ils-vm03"
segment_count = 1

segment1 {
start_extent = 0
extent_count = 468700 # 1.78795 Terabytes

type = "thin-pool"
metadata = "dataslow_tmeta"
pool = "dataslow_tdata"
transaction_id = 4
# has been transaction_id = 6
...
---
root@proxmox:/# vgcfgrestore dataslow --file /root/dataslow-orig1.vg --force

root@proxmox:/# lvchange -ay dataslow
device-mapper: reload ioctl on (252:4) failed: No data available
device-mapper: reload ioctl on (252:4) failed: No data available

**Comment by mingnus** [comment]
I see. Unfortunately, we don't guarantee the volumes are 100% recoverable if they were deleted by a normal lvm/dmsetup command, and it's not an issue of thin-provisioning-tools. Try repairing a thin-pool metadata *immediately* after deleting a volume gives a higher chance of data recovery. However, in this case, there were subsequent writes to the `vm-3010-disk-0` after deleting `vm-3004-disk-0`, making the metadata entries for `vm-3010-disk-0` got overwritten and not possible to fully recovered.

The best I can do now is retrieving the metadata at the point of time *before* deleting the two volumes. Result shows that around 1.1% (17376/1526020) of data blocks in `vm-3010-disk-0` are missing. Just uncompress the attached file  [thin_dump_override.tar.gz](https://github.com/user-attachments/files/15535940/thin_dump_override.tar.gz), thin_restore it to a new metadata volume (1GB is far enough), then swap the pool metadata.

```
# lvcreate dataslow --size 1g --name dataslow_meta1
# thin_restore -i thin_dump_override.txt -o /dev/dataslow/dataslow_meta1
# lvconvert dataslow/dataslow --swapmetadata --poolmetadata dataslow_meta1
```

**Comment by infphq** [comment]
The two VM images were rescued:

root@proxmox:~# lvcreate dataslow --size 1g --name dataslow_meta1
  Volume group "dataslow" has insufficient free space (128 extents): 256 required.

root@proxmox:~# lvcreate dataslow --size 512m --name dataslow_meta1
  Logical volume "dataslow_meta1" created.
  WARNING: This metadata update is NOT backed up.

root@proxmox:~# thin_restore -i thin_dump_override.txt -o /dev/dataslow/dataslow_meta1

root@proxmox:~# lvscan 
  inactive          '/dev/dataslow/dataslow' [1.79 TiB] inherit
  inactive          '/dev/dataslow/vm-3004-disk-0' [96.00 GiB] inherit
  inactive          '/dev/dataslow/vm-3010-disk-0' [96.00 GiB] inherit
  inactive          '/dev/dataslow/dataslow_meta0' [15.81 GiB] inherit
  ACTIVE            '/dev/dataslow/dataslow_meta1' [512.00 MiB] inherit
  ACTIVE            '/dev/pve/data' [265.18 GiB] inherit
  ACTIVE            '/dev/pve/swap' [64.00 GiB] inherit
  ACTIVE            '/dev/pve/root' [96.00 GiB] inherit
  ACTIVE            '/dev/pve/data_meta0' [2.71 GiB] inherit

root@proxmox:~# lvconvert dataslow/dataslow --swapmetadata --poolmetadata dataslow_meta1
Do you want to swap metadata of dataslow/dataslow pool with metadata volume dataslow/dataslow_meta1? [y/n]: y
  WARNING: This metadata update is NOT backed up.

root@proxmox:~# lvscan 
  inactive          '/dev/dataslow/dataslow' [1.79 TiB] inherit
  inactive          '/dev/dataslow/vm-3004-disk-0' [96.00 GiB] inherit
  inactive          '/dev/dataslow/vm-3010-disk-0' [96.00 GiB] inherit
  inactive          '/dev/dataslow/dataslow_meta0' [15.81 GiB] inherit
  inactive          '/dev/dataslow/dataslow_meta1' [15.81 GiB] inherit
  ACTIVE            '/dev/pve/data' [265.18 GiB] inherit
  ACTIVE            '/dev/pve/swap' [64.00 GiB] inherit
  ACTIVE            '/dev/pve/root' [96.00 GiB] inherit
  ACTIVE            '/dev/pve/data_meta0' [2.71 GiB] inherit

root@proxmox:~# vgchange -ay dataslow
  5 logical volume(s) in volume group "dataslow" now active

root@proxmox:~# lvscan 
  ACTIVE            '/dev/dataslow/dataslow' [1.79 TiB] inherit
  ACTIVE            '/dev/dataslow/vm-3004-disk-0' [96.00 GiB] inherit
  ACTIVE            '/dev/dataslow/vm-3010-disk-0' [96.00 GiB] inherit
  ACTIVE            '/dev/dataslow/dataslow_meta0' [15.81 GiB] inherit
  ACTIVE            '/dev/dataslow/dataslow_meta1' [15.81 GiB] inherit
  ACTIVE            '/dev/pve/data' [265.18 GiB] inherit
  ACTIVE            '/dev/pve/swap' [64.00 GiB] inherit
  ACTIVE            '/dev/pve/root' [96.00 GiB] inherit
  ACTIVE            '/dev/pve/data_meta0' [2.71 GiB] inherit


Thank you once again!

**Comment by mingnus** [comment]
It looks like the VG is nearly full. Maybe you could remove the `dataslow_meta1` after backup it up with thin_metadata_pack, to prevent running out of pool metadata space in the future.

**Comment by infphq** [comment]
Thank you very much for your advice!
