### ISSUE TITLE
Please help with broken thin pool

### ISSUE THREAD

**Issue by qrkot** [jthornber/thin-provisioning-tools#311]
Hello,

We use standard Proxmox installation which creates an LVM thin pool for default storage. In our case the storage is 4.5Tb and we managed to put 3 VMs on it. 
```bash
root@coruscant:~# pvs -a
  PV         VG  Fmt  Attr PSize PFree  
  /dev/sda2           ---     0       0 
  /dev/sda3  pve lvm2 a--  4,54t <16,25g
  /dev/sdb1           ---     0       0 
  /dev/sdc1           ---     0       0 

root@coruscant:~# vgs -a
  VG  #PV #LV #SN Attr   VSize VFree  
  pve   1   7   0 wz--n- 4,54t <16,25g

root@coruscant:~# lvs -a --option +devices
  LV              VG  Attr       LSize   Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert Devices           
  data            pve twi---tz--  <4,40t                                                     data_tdata(0)     
  [data_tdata]    pve Twi-------  <4,40t                                                     /dev/sda3(25600)  
  [data_tmeta]    pve ewi------- <15,88g                                                     /dev/sda3(1177854)
  [lvol0_pmspare] pve ewi------- <15,88g                                                     /dev/sda3(1181919)
  root            pve -wi-ao----  96,00g                                                     /dev/sda3(1024)   
  swap            pve -wi-ao----   4,00g                                                     /dev/sda3(0)      
  vm-110-disk-0   pve Vwi---tz-- 200,00g data                                                                  
  vm-110-disk-1   pve Vwi---tz-- 400,00g data                                                                  
  vm-111-disk-0   pve Vwi---tz--  50,00g data                                                                  
  vm-115-disk-0   pve Vwi---tz-- 500,00g data          
```

One day we've got an [Adaptec failed stripes error](https://techdocs.broadcom.com/us/en/ca-enterprise-software/it-operations-management/multi-port-monitor/10-3/reference/assess-hardware-health/check-for-failed-stripes.html) and found that the pool and our VMs are gone. `lvs` was still showing thin LVs as _active_, but any attempt to access them resulted in HW I/O error. 

Several times I tried to run `lvconvert --repair pve/data` _in place_, but with no result. We stopped the pool with `lvchange -an pve/data` and `ddrescue`'d whole `/dev/sdb` into a 4.5Tb image.

I launched a QEMU VM with Ubunu Jammy and attached the image as a disk to it. Then I tried to repare the PV as per [Redhat's instruction](https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/8/html/configuring_and_managing_logical_volumes/troubleshooting-lvm_configuring-and-managing-logical-volumes#repairing-a-disk-with-damaged-lvm-headers-and-metadata-using-the-pvck-command_troubleshooting-lvm) : `pvck --repair -f /etc/lvm/backup/pve /dev/sdb3` -- it was complaining on "unknown option" `thin-pool+CROP_METADATA`. I found no info on what to do with it, and simply deleted `+CROP_METADATA` parts. After that `pvck` worked seemingly Ok.

Then I run `lvconvert --repair pve/data` again. I presumed it recovered something since it created new `data_tmeta` and `data_meta0`. But now it seems to me it didn't repair anything, just cleaned all the metadata...

I tried some approaches from [here](https://github.com/jthornber/thin-provisioning-tools/issues/252), [here](https://habr.com/ru/articles/592855/), and [here](https://github.com/traktofon/thinpool-unscramble), but they doesn't seem to work out.

Currently my LVM looks like this:
```
ubuntu@ubuntu:~$ sudo lvs -a
  LV                VG  Attr       LSize   Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
  data              pve twi---tz--  <4.40t                                                    
  data_meta0        pve -wi-a----- <15.88g                                                    
  data_meta0_repair pve -wi-ao----  15.00g                                                    
  [data_tdata]      pve Twi-------  <4.40t                                                    
  [data_tmeta]      pve ewi------- <15.88g                                                    
  [lvol1_pmspare]   pve ewi------- <15.88g                                                    
  vm-110-disk-0     pve Vwi---tz-- 200.00g data                                               
  vm-110-disk-1     pve Vwi---tz-- 400.00g data                                               
  vm-111-disk-0     pve Vwi---tz--  50.00g data                                               
  vm-115-disk-0     pve Vwi---tz-- 500.00g data                                               
```

- `data_tmeta` is "repaired" meta
-  `data_meta0` is a backup of original broken meta, I presume
-  `data_meta0_repair` is a meta I tried to create with `thin_repair data_meta0`

`tnin_dump` doesn't work on either:
```
sudo thin_dump -v /dev/mapper/pve-data_tmeta 
<superblock uuid="" time="0" transaction="8" version="2" data_block_size="128" nr_data_blocks="73744256"></superblock>

ubuntu@ubuntu:~$ sudo thin_dump -v /dev/mapper/pve-data_meta0
node error: checksum error AgR0eAMA, effecting keys [..]
```

`thin_dump -v --repair /dev/pve/data_meta0 -o dump.xml &> ./dump.out` produces empty `dump.xml` and 24M `dump.out` with lines:
```
device candidates (390453):
b=221, nr_devices=4, nr_mappings=7247832, max_tid=7, age=0
b=593, nr_devices=4, nr_mappings=7198211, max_tid=7, age=0
...
b=4160974, nr_devices=4, nr_mappings=7359407, max_tid=7, age=0
b=4161369, nr_devices=4, nr_mappings=7310140, max_tid=7, age=0

compatible roots (0):
no compatible roots found
```

Pool activation doesn't work too:
```
ubuntu@ubuntu:~$ sudo lvchange -ay pve/data
[79316.617250] device-mapper: thin: 253:4: metadata device (4145152 blocks) too small: expected 4161600
[79316.619027] device-mapper: table: 253:4: thin-pool: preresume failed, error = -22
  device-mapper: resume ioctl on  (253:4) failed: Invalid argument
  Unable to resume pve-data-tpool (253:4).
```
Maybe the problem is that my `pdata_tools` were 0.9.0 ?

I managed to pack 600M of original broken meta with `pdata_tools thin_metadata_pack /dev/pve/data_meta0`, it can be [downloaded from here](https://drive.google.com/drive/folders/1Ambt6qqhwfCM5Gq7T4YAYyfLgeugmqRp?usp=drive_link) if someone's ready to have a look and give us some advice.

Regards,
Q

**Comment by qrkot** [comment]
Well, we finally managed to recover the critical data we needed, thanks to Mr. Ming-Hung Tsai's [old manual](https://listman.redhat.com/archives/linux-lvm/2016-February/msg00038.html) and [this blog post](https://www.unixrealm.com/repair-a-thin-pool/).

It seems there's no `thin_ll_dump` tools in current `pdata_tools[_dev]` v1.0.12, they must be compiled from some old branch.

Regards,
Q

**Comment by mingnus** [comment]
I was busy on other tasks so haven't take a look until now. Which nodes do you use for restoration? There are lots of candidates.

**Comment by qrkot** [comment]
> I was busy on other tasks so haven't take a look until now. Which nodes do you use for restoration? There are lots of candidates.

Hi,
Thanks to your attention.

Actually, I choose the nodes quite at random. I tried to find ones close to the original blocks 227440 and 227444. For example:
```
  <node blocknr="227430" flags="2" key_begin="3" key_end="6" nr_entries="4" value_size="8"/>
  <node blocknr="227434" flags="2" key_begin="3" key_end="6" nr_entries="4" value_size="24"/>
```

No matter what blocks I tried, "repaired" xml still had a lot of orphans.

`./pdata_tools_dev thin_ll_dump /dev/loop7 --device-details-root=227401 --data-mapping-root=227407 -o meta_reroot.xml` was the last variant, I believe. 

```
~$ sudo thin_check -vvv /dev/loop6
TRANSACTION_ID=8
METADATA_FREE_BLOCKS=4094739
number of devices to check: 4
reading internal nodes: 11.557707ms
reading leaf nodes: 268.410894ms
counting mapped blocks: 8.955496ms
nr internal nodes: 491
nr leaves: 61535
checking mapped blocks: 2.677µs
checking mapped blocks: 250ns
checking data space map: 566.038918ms
checking metadata space map: 30.702506ms
```

Then I patched the original metadata, restored it and swapped, as per the manual. After that I managed to activate `vm-110-disk-0`, the only VM we actually wanted back. Then I `dd`-ed it right from the device into an image. The image seems Ok, it's bootable and even FS seem not demaged.

BTW, LVM on Ununtu 22 doesn't understand `thin-pool+CROPPED-METADATA` option, but LVM on Debian 12 does.

**Comment by mingnus** [comment]
> Actually, I choose the nodes quite at random. I tried to find ones close to the original blocks 227440 and 227444.

Smart. It's good to choose the nodes close to that in the superblock.

One thing worth mention is that the details tree is being updated after the mapping tree, thus in most case, the details tree root is placed in the higher address than the mapping tree. The root pairs in (mapping_tree, details_tree) might be (227387, 227391), (227397, 227401), (227407, 227412), (227418, 227424), (227430, 227434), and so on.

> No matter what blocks I tried, "repaired" xml still had a lot of orphans.

It's quite normal as the dm-thin updates metadata blocks in a round-robin way nowadays, so you'll always see the previous copy metadata blocks.

> The image seems Ok, it's bootable and even FS seem not demaged.

Glad to hear that!

> BTW, LVM on Ununtu 22 doesn't understand thin-pool+CROPPED-METADATA option, but LVM on Debian 12 does.

Do you mean the LVM in Ubuntu 22 doesn't handle metadata size beyond the size limit (15.8 GB-ish)?

**Comment by qrkot** [comment]
> Do you mean the LVM in Ubuntu 22 doesn't handle metadata size beyond the size limit (15.8 GB-ish)?
Well, maybe. I've found that Ubuntu's LVM complains about `thin-pool+CROPPED-METADATA` type option, but kinda works if `+CROPPED-METADATA` part is removed. But actually I didn't test that properly, I used a Debian-12 VM.

**Comment by mingnus** [comment]
> Well, maybe. I've found that Ubuntu's LVM complains about thin-pool+CROPPED-METADATA type option, but kinda works if +CROPPED-METADATA part is removed. But actually I didn't test that properly, I used a Debian-12 VM.

I think you're talking about the `allocation/thin_pool_crop_metadata` option. It is introduced in lvm2.03.12, while Ubuntu 22 is running lvm2.03.11, so the option is not available on Ubuntu 22.
