### ISSUE TITLE
path_tracker and damage_tracker are not updated if the first subtree root was broken

### ISSUE THREAD

**Issue by mingnus** [jthornber/thin-provisioning-tools#32]
thin_check shows incorrect output if the first subtree root of the data mapping tree was broken.

For example, there's a top-level data mapping tree storing three key-value pairs: {dev_id=1, blocknr=100}, {dev_id=2, blocknr=200}, {dev_id=3, blocknr=300}. The root block#100 of the first device was broken, and some data mappings of dev_id=2 are also broken.

thin_check shows this case as following:

<pre><code>
examining superblock
examining devices tree
examining mapping tree
  missing all mappings for devices: [4, -]
    bad checksum in btree node (block 100)
  thin device 2 is missing mappings [1234, 5678]
    bad checksum in btree node (block 3000) ... 
</code></pre>

Actually, it should be:

<pre><code>
examining superblock
examining devices tree
examining mapping tree
  thin device 1 is missing mappings [0, -]
    bad checksum in btree node (block 100)
  thin device 2 is missing mappings [1234, 5678]
    bad checksum in btree node (block 3000) ... 
</code></pre>

This is because the path_tracker and the damage_tracker are still holding the information about the top-level tree (damage_begin_ == 4). I think that this could be solved by doing update_path() in error_accessing_node():

<pre><code>
diff --git a/persistent-data/data-structures/btree_damage_visitor.h b/persistent-data/data-structures/
index 2e248e8..561ab95 100644
--- a/persistent-data/data-structures/btree_damage_visitor.h
+++ b/persistent-data/data-structures/btree_damage_visitor.h
@@ -197,6 +206,7 @@ namespace persistent_data {
 
                        error_outcome error_accessing_node(node_location const &l, block_address b,
                                                           std::string const &what) {
+                               update_path(l.path);
                                report_damage(what);
                                return btree<Levels, ValueTraits>::visitor::EXCEPTION_HANDLED;
                        }
</code></pre>

**Comment by jthornber** [comment]
You 'think' this solves the problem?  or have you tried it?

**Comment by mingnus** [comment]
Yes, I have tried. This patch only affects multi-level trees. For single-level trees, the path_tracker won't get updated in update_path().
