### ISSUE TITLE
Suggestion: Support external strip program for cross-compile

### ISSUE THREAD

**Issue by mingnus** [jthornber/thin-provisioning-tools#33]
Currently, "make install" executes install with -s option, which doesn't work for cross-compiled binary. My solution is to modify configure.ac and Makefile.in, to let the configure script accept external strip program. I don't use the "-s --strip-program=<prog>" options for install, due to some install program doesn't support the "--strip-program" option.

<pre>
diff --git a/Makefile.in b/Makefile.in
index e67b300..88dd4c1 100644
--- a/Makefile.in
+++ b/Makefile.in
@@ -93,6 +93,7 @@ SOURCE=\
 
 CC:=@CC@
 CXX:=@CXX@
+STRIP:=@STRIP@
 OBJECTS:=$(subst .cc,.o,$(SOURCE))
 TOP_DIR:=@top_srcdir@
 TOP_BUILDDIR:=@top_builddir@
@@ -112,7 +113,7 @@ MANPATH:=$(DATADIR)/man
 vpath %.cc $(TOP_DIR)
 
 INSTALL_DIR = $(INSTALL) -m 755 -d
-INSTALL_PROGRAM = $(INSTALL) -m 755 -s
+INSTALL_PROGRAM = $(INSTALL) -m 755
 INSTALL_DATA = $(INSTALL) -p -m 644
 
 ifeq ("@TESTING@", "yes")
@@ -164,6 +165,7 @@ distclean: clean
 
 install: bin/pdata_tools
        $(INSTALL_DIR) $(BINDIR)
+       $(STRIP) bin/pdata_tools
        $(INSTALL_PROGRAM) bin/pdata_tools $(BINDIR)
        ln -s -f pdata_tools $(BINDIR)/cache_check
        ln -s -f pdata_tools $(BINDIR)/cache_dump
diff --git a/configure.ac b/configure.ac
index 3e6c6a9..f5e7a2e 100644
--- a/configure.ac
+++ b/configure.ac
@@ -41,6 +41,9 @@ AC_PROG_LN_S
 AC_PROG_MAKE_SET
 AC_PROG_MKDIR_P
 AC_PROG_INSTALL
+AC_DEFUN([AC_PROG_STRIP], [AC_CHECK_TOOL(STRIP, strip, :)])
+AC_PROG_STRIP
+AC_ARG_VAR(STRIP, [Command for discarding symbols from object files])
 
 ################################################################
 dnl -- Checks for functions.
</pre>

**Comment by jthornber** [comment]
Thanks, I'll push this and your earlier patch today and make a release.

**Comment by mingnus** [comment]
I should only strip the binary $(BINDIR), not the binary in ./bin. I'll fix it in my commits.

**Comment by mingnus** [comment]
Solved by pull-request #37
