### ISSUE TITLE
Suggestion: Add AC_SYS_LARGEFILE to configure.ac for 32-bit environment

### ISSUE THREAD

**Issue by mingnus** [jthornber/thin-provisioning-tools#36]
Some code utilizes off_t and lseek(), which doesn't support 64-bit addressing if the target is 32-bit. I added AC_SYS_LARGEFILE to solve this issue.

**Comment by jthornber** [comment]
Can you fork my repo and provide me with pull requests please?  Then I can grab all this (much appreciated) stuff in one go.

**Comment by mingnus** [comment]
I need to rearrange my commits, please wait a while

**Comment by mingnus** [comment]
I have one more question: Why AC_CONFIG_HEADERS was removed by commit 73876ff5 ? My current way to support 64-bit offset for 32-bit target is enabling AC_CONFIG_HEADERS, then AC_SYS_LARGEFILE exports "#define _FILE_OFFSET_BITS 64" to configure.h, then I include configure.h in persistent-data/block.h and other necessary sources.

Some critics said that this wasn't a good solution, since that people might forget to include configure.h in some sources: https://ohse.de/uwe/articles/lfs.html

There are several ways to solve this issue:
1. (might be better) Do not rely on configure.h, use -D_FILE_OFFSET_BITS in Makefile if necessary.
2. Use 64-bit function and structures explicitly. 

Please let me know your opinions. I won't submit patch for this issue until I find a good enough solution. Thank you.

**Comment by mingnus** [comment]
This works for me, but there's no spec for the value of ac_cv_sys_file_offset_bits and ac_cv_sys_large_files. I'm not very sure whether the test condition is proper or not.

<pre>
diff --git a/Makefile.in b/Makefile.in
index e67b300..70893f1 100644
--- a/Makefile.in
+++ b/Makefile.in
@@ -97,10 +97,12 @@ OBJECTS:=$(subst .cc,.o,$(SOURCE))
 TOP_DIR:=@top_srcdir@
 TOP_BUILDDIR:=@top_builddir@
 CFLAGS+=-g -Wall -O3
+CFLAGS+=@LFS_FLAGS@
 CXXFLAGS+=-g -Wall -fno-strict-aliasing
 CXXFLAGS+=@CXXOPTIMISE_FLAG@
 CXXFLAGS+=@CXXDEBUG_FLAG@
 CXXFLAGS+=@CXX_STRERROR_FLAG@
+CXXFLAGS+=@LFS_FLAGS@
 INCLUDES+=-I$(TOP_BUILDDIR) -I$(TOP_DIR) -I$(TOP_DIR)/thin-provisioning
 LIBS:=-lstdc++ -laio -lexpat
 INSTALL:=@INSTALL@
diff --git a/configure.ac b/configure.ac
index 3e6c6a9..c576267 100644
--- a/configure.ac
+++ b/configure.ac
@@ -43,6 +43,16 @@ AC_PROG_MKDIR_P
 AC_PROG_INSTALL
 
 ################################################################
+dnl -- Check for large file support
+AC_SYS_LARGEFILE
+if test x$ac_cv_sys_file_offset_bits = x64; then
+    LFS_FLAGS+="-D_FILE_OFFSET_BITS=64"
+fi
+if test x$ac_cv_sys_large_files = x1; then
+    LFS_FLAGS+="-D_LARGE_FILES"
+fi
+
+################################################################
 dnl -- Checks for functions.
 AC_FUNC_STRERROR_R
 if test x$ac_cv_func_strerror_r_char_p = xyes; then
@@ -144,6 +154,7 @@ VERSION_PATCHLEVEL=`echo "$VER" | $AWK -F '[[(.]]' '{print $3}'`
 AC_SUBST(CXXDEBUG_FLAG)
 AC_SUBST(CXXOPTIMISE_FLAG)
 AC_SUBST(CXX_STRERROR_FLAG)
+AC_SUBST(LFS_FLAGS)
 AC_SUBST(INSTALL)
 AC_SUBST(prefix)
 AC_SUBST(RELEASE_DATE)
</pre>

**Comment by mingnus** [comment]
Solved by pull-request #37
