### ISSUE TITLE
thin_delta issue

### ISSUE THREAD

**Issue by kevin-chuang** [jthornber/thin-provisioning-tools#39]
Hi Joe Thornber,
There's a issue while I'm using thin_delta. Reproduce steps:
1. Create a virtual size 100M thin volume, name thin1g, "lvcreate -L 1000M -T vg001/mythinpool -V100M -n thinvolume".
2. Zero the 100M of thinvolume, "dd if=/dev/zero of=/dev/mapper/vg001-thinvolume bs=1M count=100 oflag=dsync".
thin_dump /dev/mapper/vg001-mythinpool_tmeta output:
`<superblock uuid="" time="2" transaction="9" data_block_size="128" nr_data_blocks="16000">
  <device dev_id="1" mapped_blocks="1600" transaction="8" creation_time="2" snap_time="2">
    <range_mapping origin_begin="0" data_begin="0" length="1600" time="2"/>
  </device>
</superblock>
`

3. Take a snapshot, named snap1, "lvcreate -s -n snap1 /dev/mapper/vg001-thinvolume".
thin_dump /dev/mapper/vg001-mythinpool_tmeta output:
`<superblock uuid="" time="3" transaction="10" data_block_size="128" nr_data_blocks="16000">
  <device dev_id="1" mapped_blocks="1600" transaction="8" creation_time="2" snap_time="3">
    <range_mapping origin_begin="0" data_begin="0" length="1600" time="2"/>
  </device>
  <device dev_id="2" mapped_blocks="1600" transaction="9" creation_time="3" snap_time="3">
    <range_mapping origin_begin="0" data_begin="0" length="1600" time="2"/>
  </device>
</superblock>
`

4. Write the 64K data to thin100m from starting address of 64K, dd if=/dev/sda of=/dev/mapper/vg001-thin100m bs=64K count=1 seek=1.
thin_dump /dev/mapper/vg001-mythinpool_tmeta output:
`<superblock uuid="" time="3" transaction="10" data_block_size="128" nr_data_blocks="16000">
  <device dev_id="1" mapped_blocks="1600" transaction="8" creation_time="2" snap_time="3">
    <single_mapping origin_block="0" data_block="0" time="2"/>
    <single_mapping origin_block="1" data_block="1600" time="3"/>
    <range_mapping origin_begin="2" data_begin="2" length="1598" time="2"/>
  </device>
  <device dev_id="2" mapped_blocks="1600" transaction="9" creation_time="3" snap_time="3">
    <range_mapping origin_begin="0" data_begin="0" length="1600" time="2"/>
  </device>
</superblock>
`

5. thin_delta --snap1 1 --snap2 2 /dev/mapper/vg001-mythinpool_tmeta
You will see the following, "left_only" is incorrect, it covers too much:
`<superblock uuid="" time="3" transaction="10" data_block_size="128" nr_data_blocks="16000">
  <diff left="1" right="2">
    <same begin="0" length="1"/>
    <left_only begin="1" length="1599"/>
  </diff>
</superblock>`

My proposed solution is below.
After apply my below fix, the output of "thin_delta --snap1 1 --snap2 2 /dev/mapper/vg001-mythinpool_tmeta" looks like:
`<superblock uuid="" time="3" transaction="10" data_block_size="128" nr_data_blocks="16000">
  <diff left="1" right="2">
    <same begin="0" length="1"/>
    <different begin="1" length="1"/>
    <same begin="2" length="1598"/>
  </diff>
</superblock>`

== outptu of "git diff thin-provisioning/thin_delta.cc" ==
--- a/thin-provisioning/thin_delta.cc
+++ b/thin-provisioning/thin_delta.cc
@@ -432,7 +432,7 @@ namespace local {
                mapping left_mapping;
                mapping right_mapping;

-               while (left_it != left.end() && right_it != right.end()) {
+               while ((left_it != left.end() || left_mapping.len_) && (right_it != right.end() || right_mapping.len_)) {
                        if (!left_mapping.len_ && left_it != left.end())
                                left_mapping = *left_it++;

@@ -465,18 +465,24 @@ namespace local {
                        }
                }

-               while (left_it != left.end()) {
-                       left_mapping = *left_it++;
+               while (left_it != left.end() || left_mapping.len_) {
+                       if (!left_mapping.len_)
+                               left_mapping = *left_it++;

-                       if (left_mapping.len_)
+                       if (left_mapping.len_) {
                                e.left_only(left_mapping.vbegin_, left_mapping.dbegin_, left_mapping.len_);
+                               left_mapping.consume(left_mapping.len_);
+                       }
                }

-               while (right_it != right.end()) {
-                       right_mapping = *right_it++;
+               while (right_it != right.end() || right_mapping.len_) {
+                       if (!right_mapping.len_)
+                               right_mapping = *right_it++;

-                       if (right_mapping.len_)
+                       if (right_mapping.len_) {
                                e.right_only(right_mapping.vbegin_, right_mapping.dbegin_, right_mapping.len_);
+                               right_mapping.consume(right_mapping.len_);
+                       }
                }

                e.complete();

**Comment by jthornber** [comment]
Thanks for finding this Kevin.

I've incorporated your test into dmtest suite here:

https://github.com/jthornber/device-mapper-test-suite/commit/c3c2ca736c22bbb05c91c198430faf8c67cc51cd

I think all that's needed to fix it is the following though:

https://github.com/jthornber/thin-provisioning-tools/commit/768bbd2715fccbfeef214b555abfe3a1dfe20b86

Do you have other test cases that require the rest of your changes?

- Joe

**Comment by kevin-chuang** [comment]
Hi Joe, thanks for your asking.
Yes, you need another test case for the rest of changes.
1. Create a virtual size 100M thin volume, name thin100m
2. Zero the 10M of thin100m
3. Take a snapshot, named snap1
4. Write the 64K data to thin100m from starting address of 10M
5. thin_delta --snap1 1 --snap2 2 /dev/mapper/vg001-mythinpool_tmeta

The rest changes is kind of same as previous changes you have incorporated, it's to take good care of those left_mapping/right_mapping whose len_ is not Zero.

Kevin

**Comment by jthornber** [comment]
More test cases:

https://github.com/jthornber/device-mapper-test-suite/commit/4ebc0adcb2621b21e59c02ae0436ef807ccd9552

I refactored the comparison code in thin_delta:

https://github.com/jthornber/thin-provisioning-tools/commit/2461cdce43dc1d620ac910a39525948bbd25c002

https://github.com/jthornber/thin-provisioning-tools/commit/a21cee55c74b1ef7a0a3b10e1bf7777ac2cda310

All works for me now.

**Comment by kevin-chuang** [comment]
Thanks Joe, it works for me as well.
