### ISSUE TITLE
Semi-auto repair tools source committed

### ISSUE THREAD

**Issue by mingnus** [jthornber/thin-provisioning-tools#40]
Hi Joe,

As mentioned in this thread, I had committed my code to branch v0.6.2-repairtool for you to review
https://www.redhat.com/archives/linux-lvm/2016-February/msg00021.html

thin_ll_dump and thin_ll_restore are tools to "rearrange" metadata blocks. The "rearranged" metadata is described by an XML. The XML describes a metadata in "blocknr" domain, in contrast to the "key-value" domain of thin_dump and thin_restore.

The man pages are not ready (I might not have time to write it recently :( ). Here are brief descriptions:

1. thin_ll_dump output (the rearrangement XML):

    (1) device id & roots of the bottom-level data mapping trees
    (2) orphan nodes with value_size==8 or 24. Sorted by the key_begin, for uses to easily find the missing mappings (We can know the missing mappings by using thin_check).
    (3) I print the key-ranges before nr_entries and value_size for easier to read on terminal.

2. thin_ll_restore:

   (1) If the device-id was missing in details tree, then a new device with default attributes will be created.
   (2) You can specify multiple nodes under a device, then all the data mappings under these nodes will be emitted to the device.

3. thin_scan: An enhanced version of the old thin_show_blocks, that could help to know metadata layout, check physical medium error, etc.
I saw you rename thin_show_blocks to thin_show_metadata in branch 0.7-devel. Will you merge thin_scan with it?

Some ideas TODO:

1. thin_ll_check: like thin_check, but take an additional input XML to check the "rearranged" metadata, to know whether the rearrangement is good or not.
2. Allow thin_ll_dump to take an optional input XML, to see how many orphans you haven't utilize under the current rearrangement.
3. thin_ll_dump: Show the potential roots (nodes not referenced by others) among the orphan nodes

Release notes on commits:

1. show block address in exception string: as it.
2. [emitter] Preserve the flags and version entries in superblock
   This patch is backward compatible. thin_restore still works without the flags and version attributes.
3. [metadata_dumper] Support dump a bottom-level data mapping tree
4. [xml_parser] Allow element handlers to stop parsing (by calling XML_StopParser()). This is for thin_ll_restore.
5. [restore_emitter] Recount device_details::mapped_blocks_ during restore
6. [block-cache] Add check_raw() to bcache::validator, to check a buffer without throwing exception.
   The patch needs some refinement: check() should delegate its work to check_raw().
7. Add utility classes btree_detail::noop_value_visitor and btree_detail::noop_damage_visitor
   We might need to tide up such utility classes.
8. A more generic btree_detail::key_value_extractor to extract key-value pairs,
   that could replace details_extractor.
9. Allow counting_visitor to work with damaged btrees,
   so we can count the good nodes of a broken btrees, to know the orphan nodes (for thin_check and thin_ll_dump)
10. New utility class binary_block_counter extends block_counter, utilizing run_set to save memory
11. Factor out metadata counting functions to metadata_counter.{h,cc}.
    I pass a NULL space_map::ptr to mapping_tree_detail::block_traits::ref_counter(), instead of using tm->get_sm(), which looks confusing. (https://www.redhat.com/archives/dm-devel/2015-April/msg00019.html)

Other ideas:

1. code cleanup:

    (1) Factor out node validation functions from btree_damage_visitor.h (for thin_ll_dump)
    (2) Factor out open_tm() in each application
    (3) Extract the common interface between block_counter and binary_block_counter (is it necessary?)
    (4) The function metadata_dump_subtree() might not be good -- it opens a "backdoor" to access a tree not recognized by the metadata. But it has another use to allow thin_dump to dump a specific subtree (thin_dump --subtree_root=N).
    (5) Use metadata_counter.{h,cc} in thin_check
2. check memory consumption & memory leak
3. performance comparison: binary_block_counter, block_counter, std::set<uint64_t> and std::map<uint64_t, uint32_t>
4. Is it possible to unify btree_counter and btree_damage_visitor ? OR, is it good to extend btree_damage_visitor ?  (then btree_damage_visitor::seen_ won't be used).
   I think that it's a bad idea to accept BlockCounter and ValueCounter in btree_damage_visitor. So I choose to inherit btree_damage_visitor. Any side effect of setting btree_damage_visitor::avoid_repeated_visits_ to zero ?

Although thin_ll_dump & thin_ll_restore is useful, it is not easy to use for non-developers. Also, I don't intend to make it become fully automatic. Do you have any comments?

Thanks,
Ming-Hung Tsai

**Comment by jthornber** [comment]
This is all great.  I'm currenty doing dev work on the 0.7-devel branch.
In there I've added a --enable-dev-tools configure switch, which adds
things like thin_show_duplicates, thin_show_metadata,
thin_generate_metadata.  I'll add your tools in there too.

I'll email more when I've digested your work.

Thanks again,

- Joe

**Comment by mingnus** [comment]
Hi Joe,

How about thin_debug? I've been using thin_debug for a long time, and also wrote some patches for it. Do you agree to place thin_debug under the --enable-dev-tools option?

**Comment by jthornber** [comment]
I can't quite remember what it does.  It may be superceded by
thin_show_metadata (when it's finished)

**Comment by mingnus** [comment]
thin_debug is an interactive program that showing individual block content.
The only drawback is that the output is too long so I should scroll my terminal frequently.
So thin_show_metadata will have similar features?

<code>

./pdata_tools thin_debug /dev/mapper/tmeta

\> hello

Hello, world!

\> superblock

```xml
<fields>
  <field key="csum" value="3706008249"/>
  <field key="flags" value="0"/>
  <field key="blocknr" value="0"/>
  <field key="uuid" value=""/>
  <field key="magic" value="27022010"/>
  <field key="version" value="2"/>
  <field key="time" value="2206"/>
  <field key="trans id" value="4348"/>
  <field key="metadata snap" value="0"/>
  <field key="data mapping root" value="71"/>
  <field key="device details root" value="70"/>
  <field key="data block size" value="128"/>
  <field key="metadata block size" value="4096"/>
  <field key="metadata nr blocks" value="1048576"/>
  <field key="compat flags" value="0"/>
  <field key="compat ro flags" value="0"/>
  <field key="incompat flags" value="0"/>
</fields>
```
\> m1_node 71
```xml
<fields>
  <field key="csum" value="1338495141"/>
  <field key="blocknr" value="71"/>
  <field key="type" value="leaf"/>
  <field key="nr entries" value="74"/>
  <field key="max entries" value="252"/>
  <field key="value size" value="8"/>
  <fields>
    <field key="key" value="1"/>
    <field key="value" value="7042"/>
  </fields>
  <fields>
    <field key="key" value="2"/>
    <field key="value" value="20489"/>
  </fields>
  <fields>
    <field key="key" value="3"/>
    <field key="value" value="20920"/>
  </fields>
  ...
</field>
```
\> m2_node 7042
```xml
<fields>
  <field key="csum" value="2595986957"/>
  <field key="blocknr" value="7042"/>
  <field key="type" value="internal"/>
  <field key="nr entries" value="105"/>
  <field key="max entries" value="252"/>
  <field key="value size" value="8"/>
  <fields>
    <field key="key" value="0"/>
    <field key="value" value="7295"/>
  </fields>
  <fields>
    <field key="key" value="17926"/>
    <field key="value" value="7296"/>
  </fields>
  <fields>
    <field key="key" value="33802"/>
    <field key="value" value="7423"/>
  </fields>
  ...
</fields>
```
\> detail_node 70
```xml
<fields>
  <field key="csum" value="2073716958"/>
  <field key="blocknr" value="70"/>
  <field key="type" value="leaf"/>
  <field key="nr entries" value="74"/>
  <field key="max entries" value="126"/>
  <field key="value size" value="24"/>
  <fields>
    <field key="key" value="1"/>
    <field key="mapped blocks" value="1681015"/>
    <field key="transaction id" value="0"/>
    <field key="creation time" value="0"/>
    <field key="snap time" value="2206"/>
  </fields>
  ...
</fields>
```
</code>

**Comment by jthornber** [comment]
Yep, very similar, current screenshot:

https://www.dropbox.com/s/0jfrxf5ddaiqpby/thin_show_metadata.png?dl=0

I'm going to try switching to opengl rather than ncurses this weekend so I
can use shades of colours to show how linear/fragmented mappings are.

**Comment by mingnus** [comment]
Sounds cool!  The way to visualize metadata has puzzled me for a long time. Hope that it could help.

**Comment by jthornber** [comment]
All code merged.  Thanks again.
