### ISSUE TITLE
LDFLAGS not honoured by configure

### ISSUE THREAD

**Issue by tmakatos** [jthornber/thin-provisioning-tools#42]
I tried statically compiling ```thin-provisioning-tools``` using ```./configure LDFLAGS="-static"``` but the ```LDFLAGS``` does not end up in the Makefile. Manually adding ```LDFLAGS="-static"``` to the Makefile and then compiling works fine.

**Comment by jthornber** [comment]
Is the --enable-static-cxx option to ./configure enough?  Or do you want
all the libraries linked statically?

**Comment by tmakatos** [comment]
It's not enough I'm afraid, I need all of them to be linked statically.

**Comment by jthornber** [comment]
ok

**Comment by tmakatos** [comment]
PR #50 addresses this issue.

**Comment by tmakatos** [comment]
PR #50 merged, closing issue.
