### ISSUE TITLE
extracting allocation information in binary format

### ISSUE THREAD

**Issue by tmakatos** [jthornber/thin-provisioning-tools#44]
I need to supply the allocation information to an external application. ```thin_dump``` does provide this information however it's either in XML or human readable format, and converting this into a bitmap might take too long, especially if the the thin LV is fragmented. Is there some flag or tool that does this, or do I need to implement myself? If there isn't anything that does what I want, I suppose I need to start looking at ```thin_dump``` (add a ``` {-f|--format} {xml|human_readable|binary}``` option and implement the actual code)?

**Comment by jthornber** [comment]
Are you implementing a backup app by any chance?

**Comment by tmakatos** [comment]
Not exactly a back-up application, but one that maintains copies of the same data, so the allocation bitmap helps knowing which piece of data to replicate in case of failure.

**Comment by tmakatos** [comment]
PR #49 addresses this issue.

**Comment by tmakatos** [comment]
Fixed by commit 6c4f3ad2ff45567023dcdfd73b2c0cc66fa51fdb.
