### ISSUE TITLE
Question about thin snapshot usage.

### ISSUE THREAD

**Issue by kevin-chuang** [jthornber/thin-provisioning-tools#52]
Hi Joe, may I have a couple a question for you about LVM if you have some time?
How could I get the thin snapshot COW-ed data usage?
For example 
I have a thin volume named thin10g and I write first 1G data, then I get the field of "Data%" belonging to thin10g is 10%. 
Then I take a snapshot named snap1 on thin10g and I write first 512M.
Then I execute "lvs -a", I can see the value of the field "Data%" belonging to snap1 is also 10%. But this 10% is not what I want, what I want is 5%.
I only write 512M new data to thin10g since snap1 token, that means LVM only copied 512M old data from thin10g to snap1(512M/10240M = 5%).
Do you have any way to get the real usage '5%' of this snapshot?

Kevin

**Comment by jthornber** [comment]
Take a look at thin_ls in the 0.6.x series of thin-provisioning-tools.  In
particular you want -o EXCLUSIVE_SECTORS.  LVM will wrap thin_ls soon, if
it doesn't already.

**Comment by kevin-chuang** [comment]
Thanks Joe.
I tried thin_ls and the output is sort of strange.
1. I create a thin-volume named thin1g with virtual size 1G.
2. dd if=/dev/urandom of=/dev/mapper/vg1-thin1g bs=64k count=10 oflag=dsync
3. lvcreate -s --name thin1g-s1 vg1/thin1g
4. dd if=/dev/urandom of=/dev/mapper/vg1-thin1g bs=64k count=1 oflag=dsync
5. lvcreate -s --name thin1g-s2 vg1/thin1g
6. dd if=/dev/urandom of=/dev/mapper/vg1-thin1g bs=64k count=2 oflag=dsync
So far I expect thin1g-s1 usage size is 64k, and thin1g-s2 usage size is 128k
But the output of thin_ls is:
EXCLUSIVE_SECTORS
              256
              128
              128

BTW, the output of thin_dump is:
stack@k-stack3:~/proj/thin-provisioning-tools$ sudo ./bin/thin_dump -m8 /dev/mapper/vg1-thinpool_tmeta
<superblock uuid="" time="11" transaction="23" data_block_size="128" nr_data_blocks="0">
  <device dev_id="1" mapped_blocks="10" transaction="20" creation_time="9" snap_time="11">
    <range_mapping origin_begin="0" data_begin="12" length="2" time="11"/>
    <range_mapping origin_begin="2" data_begin="3" length="8" time="9"/>
  </device>
  <device dev_id="2" mapped_blocks="10" transaction="21" creation_time="10" snap_time="10">
    <range_mapping origin_begin="0" data_begin="1" length="10" time="9"/>
  </device>
  <device dev_id="3" mapped_blocks="10" transaction="22" creation_time="11" snap_time="11">
    <single_mapping origin_block="0" data_block="11" time="10"/>
    <range_mapping origin_begin="1" data_begin="2" length="9" time="9"/>
  </device>
</superblock>

**Comment by kevin-chuang** [comment]
The output of thin_dump:

```
<superblock uuid="" time="11" transaction="23" data_block_size="128" nr_data_blocks="0">
  <device dev_id="1" mapped_blocks="10" transaction="20" creation_time="9" snap_time="11">
    <range_mapping origin_begin="0" data_begin="12" length="2" time="11"/>
    <range_mapping origin_begin="2" data_begin="3" length="8" time="9"/>
  </device>
  <device dev_id="2" mapped_blocks="10" transaction="21" creation_time="10" snap_time="10">
    <range_mapping origin_begin="0" data_begin="1" length="10" time="9"/>
  </device>
  <device dev_id="3" mapped_blocks="10" transaction="22" creation_time="11" snap_time="11">
    <single_mapping origin_block="0" data_block="11" time="10"/>
    <range_mapping origin_begin="1" data_begin="2" length="9" time="9"/>
  </device>
</superblock>
```

**Comment by jthornber** [comment]
I think it's correct.  The exclusive blocks (each 64k) are:

dev 1: 12, 13
dev 2: 1
dev 3: 11

**Comment by kevin-chuang** [comment]
Joe, thanks for reply.
I think the exclusive output is correct now, but the exclusive function is not what I need.
What I need is calculating all the data sectors been written during snap2 and snap3.
Take example above, let's take another snapshot named thin1g-s3, dev_id="4",
for dev_id="3", the all data sectors been written between thin1g-s2 to thin1g-s3 is this one:
<"range_mapping origin_begin="0" data_begin="12" **length="2"** **time="11"**\>
How could I find this one? I can traverse all mapping and find out the mapping time is equal to the creation_time of thin1g-s2 "11", hence I found this one mapping whose time="11".
So I can calculate the all data been written between thin1g-s2 to thin1g-s3 is 2 sectors.
And I can claim that thin1g-s2 this snapshot comsume 2 sectors disk space.

I'm wondering do you have any tool to satisfy my requirement?
Thanks again for your help!!
Kevin

**Comment by jthornber** [comment]
Try thin_delta

**Comment by kevin-chuang** [comment]
Thanks Joe,

thin_delta works.
