### ISSUE TITLE
thin tools should fail with active metadata

### ISSUE THREAD

**Issue by jthornber** [jthornber/thin-provisioning-tools#7]
Obviously if we're dumping a metadata snapshot it should be ok, but if we're dumping the superblock then we should try and open exclusively to stop the admin shooting himself in the foot.

**Comment by yasker** [comment]
In fact rancher-volume( https://github.com/rancher/rancher-volume ) is using thin-provisioning-tools(thin_delta) to gather the information about snapshots, and this fix(642ae6e7c273560f93e753737899add661e6f14a) broke it completely...

Could you elaborate the problem? And is there anyway around this?

**Comment by jthornber** [comment]
Ah, I'd forgotten that thin delta used the metastatic snap. Will fix next
week.

**Comment by jthornber** [comment]
Try the latest code again please.

**Comment by yasker** [comment]
I didn't see any new commits since July 7th?

**Comment by jthornber** [comment]
Sorry, I forgot to push, try now.

commit 271ff67f910

**Comment by yasker** [comment]
Still doesn't work...

Same "syscall 'open' failed: Device or resource busy"

I tried thin_dump and thin_delta both, on an active loop back device.

> sudo dmsetup table
459be014-d0da-48e6-bbeb-855f70763ad5: 0 20971520 thin 252:2 21
b154788c-5714-417c-b094-81634121d36d: 0 20971520 thin 252:2 18
linux--dev--vg-root: 0 30908416 linear 8:5 2048
linux--dev--vg-swap_1: 0 2088960 linear 8:5 30910464
rancher-volume-pool: 0 209715200 thin-pool 7:1 7:0 4096 32768 1 skip_block_zeroing

rancher-volume-pool is the one I use against, which:

> sudo losetup -a
/dev/loop0: [fc00]:547578 (/opt/data.vol)
/dev/loop1: [fc00]:547579 (/opt/metadata.vol)

Metadata mounted on /dev/loop1

Here is the command I tried:

> sudo pdata_tools thin_delta -snap1 2 -snap2 3 /dev/loop1

**Comment by jthornber** [comment]
If the pool is active you must use a metadata snapshot, otherwise you're
trying to examine data that the kernel is actively changing.

**Comment by yasker** [comment]
I see, thanks. It works for me now, though I may need to look more into details of metadata snapshot. E.g. if it's thread-safe, and if there can be more than one copy of it, and do I really need to release every time...

**Comment by jthornber** [comment]
There can only be one metadata snapshot at a time.  It's safe to run
multiple thin_deltas at the same time.  The metadata snap does degrade
performance slightly due to additional copy-on-writes of metadata pages, so
release it when you've finished.

**Comment by yasker** [comment]
Thank you Joe, that's totally cleaned my doubts!

**Comment by tmakatos** [comment]
> If the pool is active you must use a metadata snapshot, otherwise you're
trying to examine data that the kernel is actively changing.

How do I create a metadata snapshot? Is this related to creating a snapshot of the thin LV?

**Comment by tmakatos** [comment]
I found a workaround (?): dd the metadata device and then present it as a block device via loopback. thin_dump against it works fine. Is this how it is meant to work?

**Comment by jthornber** [comment]
No that is not how it is meant to work.

You take a metadata snapshot by sending a message to the dm pool target.
This creates a copy of the superblock (minus the space maps), you're
guaranteed that the mapping trees from this snapshot will not be changed,
so you can read them even though the pool is live.

Have a look at the dm test suite for some examples of use, in particular
simple examples can be found here:

https://github.com/jthornber/device-mapper-test-suite/blob/master/lib/dmtest/tests/thin-provisioning/held_root_tests.rb

(note metadata snapshots used to be known as having a 'held root' when I
first wrote it).
