### ISSUE TITLE
Is it possible to modify trees in an existed metadata?

### ISSUE THREAD

**Issue by mingnus** [jthornber/thin-provisioning-tools#70]
Hi Joe,

I'm not sure if it's possible to do that: open an existed metadata, then modify the trees. I did the following steps, then block_manager::get() throws an exception "couldn't get block" -- seems something wrong in sm_recursive::inc(). I haven't look into the code. Is that a bug, or a known limitation?

step1. create input.xml:

``` XML
<superblock uuid="" time="0" transaction="0" data_block_size="128" nr_data_blocks="16384">
</superblock>
```

step2. create an empty 16MB tmeta.bin:

``` SHELL
$ dd if=/dev/zero of=tmeta.bin bs=1M count=16
$ ./bin/pdata_tools thin_restore -i input.xml -o tmeta.bin
```

step3. then simply insert a key-value pair [10,100] to the top-level tree...

``` C++
block_manager<>::ptr bm(open_bm("tmeta.bin", block_manager<>::READ_WRITE));
metadata::ptr input_md(new metadata(bm, true));
uint64_t key[1] = {10};
input_md->mappings_top_level_->insert(key, static_cast<uint64_t>(100));
input_md->commit();
```

output:

``` SHELL
couldn't get block
```

**Comment by jthornber** [comment]
It's the intention, but few, if any tools do this, so I'd expect bugs.

**Comment by mingnus** [comment]
There are bugs in sm_recursive. Belows are patches for discussion.
I haven't well validate these patches, but at least they work for the above case.

### Blocks allocated to duplicated address

In kernel dm-thin, sm_metadata_new_block_() sets `smm->begin = *b + 1` after allocating a new block, so the metadata space map won't allocate the same block inside a recursion.
In contrast, sm_recursive doesn't do that, so a btree node and the corresponding bitmap blocks are shadowed to the same block.

e.g., For the following metadata, when I modifying the top-level tree, both the data mapping root#8 and the bitmap block#3 are shadowed to the same new block#9.
```c++
// $ dd if=/dev/zero of=tmeta.bin bs=1M count=16
// Result metadata:
//   metadata sm:
//     bitmap root: 1 
//     ref-count tree root: 2
//     bitmap: 3
//   data sm:
//     bitmap tree root: 4
//     ref-count tree root: 5
//     bitmap: 6
//   device details tree: 7
//   data mapping root: 8
block_manager<>::ptr bm(open_bm("tmeta.bin", block_manager<>::READ_WRITE));
metadata::ptr md(new metadata(bm, metadata::CREATE, 1024, 1024));
md->commit();
```

So I patch sm_recursive::inc() as following. Note that we cannot put this line inside sm_recursive::find_free(), because the recursing_lock will clear the allocated_blocks_.
(In contrast, kernel dm-thin has only one function sm_metadata_new_block_()...)

```c++
--- a/persistent-data/space-maps/recursive.cc
+++ b/persistent-data/space-maps/recursive.cc
@@ -114,6 +114,7 @@ namespace {
                                add_op(block_op(block_op::INC, b));
                        else {
                                recursing_lock lock(*this);
+                               allocated_blocks_.add(b, b + 1);
                                return sm_->inc(b);
                        }
                }

```


### Wrong shared block recognition in sm_recursive::count_possibly_greater_than_one()

transaction_manager::shadow() allocates a new block if `orig` is shared (ref-count > 1), by using sm_recursive::count_possibly_greater_than_one().
However, this function returns false-alarm -- It starts counting from one: `ref_t count = 1`, so we are not able to modify a shadowed bitmap block when doing flush_ops().

Why not using sm_recursive::get_count() ?

```c++
--- a/persistent-data/space-maps/recursive.cc
+++ b/persistent-data/space-maps/recursive.cc
@@ -136,36 +137,7 @@ namespace {
                }
 
                virtual bool count_possibly_greater_than_one(block_address b) const {
-                       recursing_const_lock lock(*this);
-                       bool gto = sm_->count_possibly_greater_than_one(b);
-                       if (!gto) {
-                               ref_t count = 1;
-
-                               // FIXME: duplication
-                               op_map::const_iterator ops_it = ops_.find(b);
-                               if (ops_it != ops_.end()) {
-                                       list<block_op>::const_iterator it, end = ops_it->second.end();
-                                       for (it = ops_it->second.begin(); it != end; ++it) {
-                                               switch (it->op_) {
-                                               case block_op::INC:
-                                                       count++;
-                                                       break;
-
-                                               case block_op::DEC:
-                                                       count--;
-                                                       break;
-
-                                               case block_op::SET:
-                                                       count = it->b_;
-                                                       break;
-                                               }
-                                       }
-                               }
-
-                               gto = count > 1;
-                       }
-
-                       return gto;
+                       return get_count(b) > 1;
```

I also have a question about sm_metadata_count_is_more_than_one() in kernel:
It doesn't query the ref-count btree. Will it lead to some side effects?

```c
static int sm_metadata_count_is_more_than_one(struct dm_space_map *sm,
                                              dm_block_t b, int *result)
{
	...

        r = sm_ll_lookup_bitmap(&smm->ll, b, &rc);
        if (r) 
                return r;

        if (rc == 3)
                /*
                 * We err on the side of caution, and always return true.
                 */
                *result = 1;
        else
                *result = rc + adjustment > 1;

        return 0;  
}
```

**Comment by mingnus** [comment]
Other questions:

* Why sm_recursive::count_possibly_greater_than_one() holds a recursing_const_lock ?
  What's the purpose of recursing_const_lock ?

* Does the ordering of recursing block operations matter?
  sm_recursive::ops_ is a map, and we might generate some more operations during flush_ops_() (I'm not sure).
  Should it be a list ?

**Comment by jthornber** [comment]
9b4c419f5914d6a1fe154cba61231f3028872734
37bd187757d587da5e551376ae5809f527241c9d
 
Every public method needs to keep track of whether it's called recursively.  That's all recursing_const_lock does.

ops_ is a map of lists, I think it's enough to keep the ops ordered for individual blocks only.
