### ISSUE TITLE
how to use thin_trim?

### ISSUE THREAD

**Issue by alexcreek** [jthornber/thin-provisioning-tools#76]
I can't figure out how to use thin_trim.  Running docker 1.12 with devicemapper and I'm trying to reclaim space with thin_trim but I can't figure out how to take the thin pool offline so trim can run. 

    # thin_trim  --metadata-dev /dev/mapper/centos-docker--pool_tmeta --data-dev /dev/mapper/centos-docker--pool_tdata
    syscall 'open' failed: Device or resource busy
    Note: you cannot run this tool with these options on live metadata.
    
I can't find any open filehandles using the devices.  Taking a metadata snapshot didn't work.  Tried deactivating the thin pool lv but then it's no longer available under /dev/mapper. 

    # lvs
      LV          VG     Attr       LSize   Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
      docker-pool centos twi-a-t--- 103.46g             80.09  38.01
      root        centos -wi-ao----  43.81g
      swap        centos -wi-ao----   1.00g

I've exhausted all the docs I could find on this so any help would be greatly appreciated ;)

**Comment by jthornber** [comment]
The thin-pool is built out of two devices, a metadata device and a data device.  You need to deactivate the pool and then run thin_trim on those separate devices:

thin_trim --metadata-dev <dev> --data-dev <dev>

Identify the metadata and data dev by doing an lvs -a, I'm told docker will have given the devs sensible names.

**Comment by rhvgoyal** [comment]
This probably is lvm thin pool. That means data and metadata volumes are managed internally by lvm. If he deactivates the pool, I am not sure lvm will allow him to access data/metadata volumes directly. Is there a way to do that.

**Comment by zkabelac** [comment]
This operation is not directly supported by lvm2.
So the best user can do -   make sure there is no running thin device (any thin-pool user).
Then with  'dmsetup remove centos-docker--pool '   to remove thin-pool target  - so only _tdata & _tmeta devices are available.
Verify with 'dmsetup info -c'  they are NOT in use  (see 'dmsetup ls --tree' for users).
Proceed your 'thin_trim'  workflow.
After all is done - 'dmsetup remove' remaining devices (_tdate & _tmeta)
Run regular  'lvchange -ay XXX' operation to start thin-pool again.

**Comment by alexcreek** [comment]
Thanks @zkabelac!  Worked like a charm ;)
