### ISSUE TITLE
thin-provions can not handle dasd disk

### ISSUE THREAD

**Issue by thesues** [jthornber/thin-provisioning-tools#9]
hi,maintainer.
  the default sector size of dasd(IBM s390 ) is 4k.  But the default Alignment is only 512.
So when we use DIRECT_IO to read from dasd disk. the read will alway fail.
So I suggest if we do not want to use ioctl to check every block's sector size, why not 
set Alignment = 4096? I think 4096 alignment is big enough.

**Comment by jthornber** [comment]
These days we use PAGE_SIZE alignment, so it will be at least 4096.
