### ISSUE TITLE
thin metadata sb_.version_ =1 

### ISSUE THREAD

**Issue by CodeImp** [jthornber/thin-provisioning-tools#90]
Thin-provisioning do not support modern thin devices.
Since Linux kernel 3.14 
http://elixir.free-electrons.com/linux/v3.14/source/drivers/md/dm-thin-metadata.c 
#define THIN_VERSION 2 
May be
		if (sb_.version_ > 2)
			throw runtime_error("unknown metadata version"); 
?

**Comment by jthornber** [comment]
Which version of the thinp tools are you using?

**Comment by CodeImp** [comment]
this
https://github.com/jthornber/thin-provisioning-tools/blob/master/thin-provisioning/metadata.cc
line 62

**Comment by mingnus** [comment]
That's also my question - What's the different between version-2 and version-1 metadata? Does that mean format changes?

**Comment by jthornber** [comment]
https://github.com/torvalds/linux/commit/07f2b6e0382ec4c59887d5954683f1a0b265574e

It's the NEEDS_CHECK flag.  See the above patch from 2014.

**Comment by jthornber** [comment]
Fixed
